import type { ConsoleAccount, ConsoleConfigEntry } from "./consoleModels";

export type ConsoleSettingKind = "text" | "textarea" | "password" | "number" | "checkbox" | "select" | "readonly";

export type ConsoleSettingField = {
  key: string;
  label: string;
  description: string;
  kind: ConsoleSettingKind;
  placeholder?: string;
  rows?: number;
  options?: Array<{ value: string; label: string }>;
};

export type ConsoleSettingGroup = {
  id: string;
  title: string;
  description: string;
  fields: readonly ConsoleSettingField[];
};

export type ConsoleModelProfile = {
  id: string;
  name: string;
  values: Record<string, string>;
  createdAt: number;
  updatedAt: number;
};

const MODEL_PROFILES_VERSION = 1;
const MODEL_PROFILE_KEY = "model_profiles";
const MAX_PROFILE_NAME_LENGTH = 80;

export const AGENT_MODEL_FIELDS: readonly ConsoleSettingField[] = [
  {
    key: "config/ai/provider",
    label: "Provider",
    description: "LLM provider used by agent runs.",
    kind: "text",
    placeholder: "workers-ai",
  },
  {
    key: "config/ai/model",
    label: "Model",
    description: "Model identifier passed to the selected provider.",
    kind: "text",
    placeholder: "@cf/nvidia/nemotron-3-120b-a12b",
  },
  {
    key: "config/ai/api_key",
    label: "API key",
    description: "Provider credential. Leave empty for local or bound providers.",
    kind: "password",
    placeholder: "sk-...",
  },
  {
    key: "config/ai/reasoning",
    label: "Reasoning",
    description: "Reasoning effort hint for models that support extended thinking.",
    kind: "select",
    options: [
      { value: "off", label: "Off" },
      { value: "minimal", label: "Minimal" },
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
      { value: "xhigh", label: "Extra High" },
    ],
  },
  {
    key: "config/ai/max_tokens",
    label: "Max tokens",
    description: "Upper bound for generated response size.",
    kind: "number",
  },
  {
    key: "config/ai/max_context_bytes",
    label: "Max context bytes",
    description: "Maximum bytes of home context injected into prompts.",
    kind: "number",
  },
];

export const MODEL_PROFILE_FIELDS: readonly ConsoleSettingField[] = AGENT_MODEL_FIELDS;
export const MODEL_PROFILE_SECRET_FIELDS: readonly ConsoleSettingField[] = MODEL_PROFILE_FIELDS
  .filter((field) => isSensitiveSettingKey(field.key));

export const TOOL_MODEL_GROUPS: readonly ConsoleSettingGroup[] = [
  {
    id: "image-read",
    title: "Image Reader",
    description: "Converts image attachments into text context.",
    fields: [
      {
        key: "config/ai/image/read/provider",
        label: "Provider",
        description: "Provider used to describe images.",
        kind: "text",
        placeholder: "workers-ai",
      },
      {
        key: "config/ai/image/read/model",
        label: "Model",
        description: "Vision model used to generate image descriptions.",
        kind: "text",
        placeholder: "@cf/google/gemma-4-26b-a4b-it",
      },
      {
        key: "config/ai/image/read/api_key",
        label: "API key",
        description: "Optional credential. Falls back to the agent API key when empty.",
        kind: "password",
        placeholder: "sk-...",
      },
      {
        key: "config/ai/image/read/input_format",
        label: "Input mode",
        description: "Request shape used when sending image content.",
        kind: "select",
        options: [
          { value: "auto", label: "Auto" },
          { value: "chat", label: "Chat vision" },
          { value: "image", label: "Raw image" },
        ],
      },
      {
        key: "config/ai/image/read/max_bytes",
        label: "Max bytes",
        description: "Maximum stored image size sent to the image-reading model.",
        kind: "number",
      },
      {
        key: "config/ai/image/read/max_tokens",
        label: "Max tokens",
        description: "Maximum text tokens generated by the image-reading model.",
        kind: "number",
      },
      {
        key: "config/ai/image/read/timeout_ms",
        label: "Timeout",
        description: "Maximum time to wait for image description generation.",
        kind: "number",
      },
      {
        key: "config/ai/image/read/prompt",
        label: "Prompt",
        description: "Instruction used when converting images into text context.",
        kind: "textarea",
        rows: 4,
      },
    ],
  },
  {
    id: "image-generation",
    title: "Image Generator",
    description: "Default model stack for text-to-image and image editing.",
    fields: [
      {
        key: "config/ai/image/generation/provider",
        label: "Provider",
        description: "Provider used for image generation.",
        kind: "text",
        placeholder: "workers-ai",
      },
      {
        key: "config/ai/image/generation/model",
        label: "Model",
        description: "Default model for image generation.",
        kind: "text",
        placeholder: "@cf/black-forest-labs/flux-1-schnell",
      },
      {
        key: "config/ai/image/generation/api_key",
        label: "API key",
        description: "Optional credential. Falls back to the agent API key when empty.",
        kind: "password",
        placeholder: "sk-...",
      },
    ],
  },
  {
    id: "transcription",
    title: "Transcription",
    description: "Speech-to-text model stack for audio attachments.",
    fields: [
      {
        key: "config/ai/transcription/provider",
        label: "Provider",
        description: "Provider used by transcription requests.",
        kind: "text",
        placeholder: "workers-ai",
      },
      {
        key: "config/ai/transcription/model",
        label: "Model",
        description: "Speech-to-text model used for audio attachments.",
        kind: "text",
        placeholder: "@cf/openai/whisper-large-v3-turbo",
      },
      {
        key: "config/ai/transcription/api_key",
        label: "API key",
        description: "Optional credential. Falls back to the agent API key when empty.",
        kind: "password",
        placeholder: "sk-...",
      },
      {
        key: "config/ai/transcription/max_bytes",
        label: "Max bytes",
        description: "Maximum audio payload size accepted for transcription.",
        kind: "number",
      },
    ],
  },
  {
    id: "speech",
    title: "Speech",
    description: "Text-to-speech model stack.",
    fields: [
      {
        key: "config/ai/speech/provider",
        label: "Provider",
        description: "Provider used by speech synthesis.",
        kind: "text",
        placeholder: "workers-ai",
      },
      {
        key: "config/ai/speech/model",
        label: "Model",
        description: "Text-to-speech model used by speech synthesis.",
        kind: "text",
        placeholder: "@cf/deepgram/aura-2-en",
      },
      {
        key: "config/ai/speech/api_key",
        label: "API key",
        description: "Optional credential. Falls back to the agent API key when empty.",
        kind: "password",
        placeholder: "sk-...",
      },
      {
        key: "config/ai/speech/speaker",
        label: "Speaker",
        description: "Default voice or speaker.",
        kind: "text",
        placeholder: "luna",
      },
      {
        key: "config/ai/speech/encoding",
        label: "Encoding",
        description: "Default audio encoding for synthesized speech.",
        kind: "text",
        placeholder: "mp3",
      },
      {
        key: "config/ai/speech/max_chars",
        label: "Max chars",
        description: "Maximum normalized text length accepted for speech synthesis.",
        kind: "number",
      },
      {
        key: "config/ai/speech/timeout_ms",
        label: "Timeout",
        description: "Maximum time to wait for speech synthesis.",
        kind: "number",
      },
    ],
  },
];

export const RUNTIME_SETTING_GROUPS: readonly ConsoleSettingGroup[] = [
  {
    id: "shell",
    title: "Shell",
    description: "Defaults for native shell execution.",
    fields: [
      {
        key: "config/shell/timeout_ms",
        label: "Timeout",
        description: "Default timeout for native shell execution.",
        kind: "number",
      },
      {
        key: "config/shell/network_enabled",
        label: "Network",
        description: "Allow network-capable shell tools such as curl and wget.",
        kind: "checkbox",
      },
      {
        key: "config/shell/max_output_bytes",
        label: "Max output bytes",
        description: "Maximum captured shell output before truncation.",
        kind: "number",
      },
    ],
  },
  {
    id: "server",
    title: "Server",
    description: "Instance metadata used by system tools and scheduling.",
    fields: [
      {
        key: "config/server/name",
        label: "Instance name",
        description: "Human-readable name shown by system tools and shell surfaces.",
        kind: "text",
      },
      {
        key: "config/server/timezone",
        label: "Timezone",
        description: "IANA timezone used for scheduling and timestamps.",
        kind: "text",
        placeholder: "Europe/Amsterdam",
      },
      {
        key: "config/server/version",
        label: "Version",
        description: "Current server version reported by the runtime.",
        kind: "readonly",
      },
    ],
  },
];

export function viewerAccountForSettings(accounts: readonly ConsoleAccount[]): ConsoleAccount | null {
  return accounts.find((account) => account.relation === "self")
    ?? accounts.find((account) => account.uid === 0)
    ?? null;
}

export function buildUserAiOverrideKey(uid: number, systemKey: string): string {
  if (!systemKey.startsWith("config/ai/")) {
    throw new Error(`Cannot build user AI override for non-AI key: ${systemKey}`);
  }
  return `users/${uid}/${systemKey.slice("config/".length)}`;
}

export function modelProfilesConfigKey(uid: number): string {
  return `users/${uid}/ai/${MODEL_PROFILE_KEY}`;
}

export function isModelProfilesConfigKey(key: string): boolean {
  return /^users\/\d+\/ai\/model_profiles$/.test(key);
}

export function modelProfileSecretConfigKey(uid: number, profileId: string, fieldKey: string): string {
  if (!fieldKey.startsWith("config/ai/")) {
    throw new Error(`Cannot build model profile secret key for non-AI key: ${fieldKey}`);
  }
  const normalizedProfileId = normalizeProfileId(profileId);
  if (!normalizedProfileId) {
    throw new Error("Profile id is required");
  }
  return `users/${uid}/ai/${MODEL_PROFILE_KEY}/${normalizedProfileId}/${fieldKey.slice("config/ai/".length)}`;
}

export function configEntryForKey(
  config: readonly ConsoleConfigEntry[],
  key: string,
): ConsoleConfigEntry | null {
  return config.find((entry) => entry.key === key) ?? null;
}

export function configValueForKey(
  config: readonly ConsoleConfigEntry[],
  key: string,
): string {
  const entry = configEntryForKey(config, key);
  return entry && !entry.redacted ? entry.value : "";
}

export function configValueMap(config: readonly ConsoleConfigEntry[]): Record<string, string> {
  const values: Record<string, string> = {};
  for (const entry of config) {
    if (!entry.redacted) {
      values[entry.key] = entry.value;
    }
  }
  return values;
}

export function effectiveAiValuesForViewer(
  config: readonly ConsoleConfigEntry[],
  uid: number | null | undefined,
): Record<string, string> {
  const values: Record<string, string> = {};
  for (const field of allAiSettingFields()) {
    values[field.key] = configValueForKey(config, field.key);
  }
  if (typeof uid !== "number" || !Number.isFinite(uid)) {
    return values;
  }
  for (const field of allAiSettingFields()) {
    const overrideValue = configValueForKey(config, buildUserAiOverrideKey(uid, field.key));
    if (overrideValue !== "") {
      values[field.key] = overrideValue;
    }
  }
  return values;
}

export function modelProfilesForConfig(
  config: readonly ConsoleConfigEntry[],
  uid: number | null | undefined,
): ConsoleModelProfile[] {
  if (typeof uid !== "number" || !Number.isFinite(uid)) {
    return [];
  }
  const raw = configValueForKey(config, modelProfilesConfigKey(uid));
  if (!raw.trim()) {
    return [];
  }

  try {
    const payload = JSON.parse(raw) as { profiles?: unknown[] };
    const profiles = Array.isArray(payload.profiles) ? payload.profiles : [];
    return profiles
      .map(normalizeModelProfile)
      .filter((profile): profile is ConsoleModelProfile => profile !== null)
      .map((profile) => hydrateModelProfileSecrets(config, uid, profile))
      .sort((left, right) => right.updatedAt - left.updatedAt || left.name.localeCompare(right.name));
  } catch {
    return [];
  }
}

export function serializeModelProfiles(profiles: readonly ConsoleModelProfile[]): string {
  return JSON.stringify({
    version: MODEL_PROFILES_VERSION,
    profiles: profiles.map((profile) => ({
      id: profile.id,
      name: normalizeProfileName(profile.name),
      values: normalizeProfileStorageValues(profile.values),
      createdAt: profile.createdAt,
      updatedAt: profile.updatedAt,
    })),
  });
}

export function redactModelProfilesConfigValue(raw: string): string {
  if (!raw.trim()) {
    return raw;
  }
  try {
    const payload = JSON.parse(raw) as Record<string, unknown>;
    if (!payload || typeof payload !== "object" || !Array.isArray(payload.profiles)) {
      return raw;
    }
    return JSON.stringify({
      ...payload,
      profiles: payload.profiles.map(redactModelProfileSecrets),
    });
  } catch {
    return raw;
  }
}

export function createModelProfile(
  profiles: readonly ConsoleModelProfile[],
  name: string,
  values: Record<string, string>,
  now = Date.now(),
): ConsoleModelProfile[] {
  const normalizedName = normalizeProfileName(name);
  if (!normalizedName) {
    throw new Error("Profile name is required");
  }
  const existing = profiles.find((profile) => profile.name.toLowerCase() === normalizedName.toLowerCase());
  if (existing) {
    return updateModelProfile(profiles, existing.id, normalizedName, values, now);
  }
  return [
    {
      id: uniqueProfileId(profiles, normalizedName),
      name: normalizedName,
      values: normalizeProfileValues(values),
      createdAt: now,
      updatedAt: now,
    },
    ...profiles,
  ];
}

export function updateModelProfile(
  profiles: readonly ConsoleModelProfile[],
  profileId: string,
  name: string,
  values: Record<string, string>,
  now = Date.now(),
): ConsoleModelProfile[] {
  const normalizedName = normalizeProfileName(name);
  if (!normalizedName) {
    throw new Error("Profile name is required");
  }
  return profiles.map((profile) => profile.id === profileId
    ? {
        ...profile,
        name: normalizedName,
        values: normalizeProfileValues(values),
        updatedAt: now,
      }
    : profile);
}

export function deleteModelProfile(
  profiles: readonly ConsoleModelProfile[],
  profileId: string,
): ConsoleModelProfile[] {
  return profiles.filter((profile) => profile.id !== profileId);
}

export function profileValuesFromDrafts(values: Record<string, string>): Record<string, string> {
  return normalizeProfileValues(values);
}

export function modelProfileSummary(values: Record<string, string>): string {
  const provider = cleanValue(values["config/ai/provider"]) || "provider";
  const model = cleanValue(values["config/ai/model"]) || "model";
  const reasoning = cleanValue(values["config/ai/reasoning"]) || "default";
  return `${provider} / ${modelDisplayName(model)} / reasoning ${reasoning}`;
}

export function modelDisplayName(value: string): string {
  const shortName = shortModelName(value);
  if (!shortName) {
    return "";
  }
  return shortName
    .split(/[-_\s.]+/)
    .filter(Boolean)
    .map(formatModelNamePart)
    .join(" ");
}

export function shortModelName(value: string): string {
  const normalized = cleanValue(value);
  if (!normalized) {
    return "";
  }
  if (normalized.startsWith("@cf/")) {
    const parts = normalized.split("/").filter(Boolean);
    return parts[parts.length - 1] || normalized;
  }
  if (normalized.includes("/")) {
    const parts = normalized.split("/").filter(Boolean);
    return parts[parts.length - 1] || normalized;
  }
  return normalized;
}

function formatModelNamePart(part: string): string {
  const upper = part.toUpperCase();
  if (/^[a-z]?\d+[a-z]?$/i.test(part) || upper.length <= 3) {
    return upper;
  }
  return `${part.charAt(0).toUpperCase()}${part.slice(1)}`;
}

export function isSensitiveSettingKey(key: string): boolean {
  return /(?:^|\/|_)(?:api[_-]?key|password|secret|token|credential)(?:$|\/|_)/i.test(key);
}

export function allAiSettingFields(): ConsoleSettingField[] {
  return [
    ...AGENT_MODEL_FIELDS,
    ...TOOL_MODEL_GROUPS.flatMap((group) => group.fields),
  ];
}

export function allModeledSettingKeys(): Set<string> {
  return new Set([
    ...allAiSettingFields(),
    ...RUNTIME_SETTING_GROUPS.flatMap((group) => group.fields),
  ].map((field) => field.key));
}

function normalizeModelProfile(raw: unknown): ConsoleModelProfile | null {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return null;
  }
  const record = raw as Record<string, unknown>;
  const id = normalizeProfileId(record.id);
  const name = normalizeProfileName(record.name);
  if (!id || !name) {
    return null;
  }
  return {
    id,
    name,
    values: normalizeProfileValues(
      record.values && typeof record.values === "object" && !Array.isArray(record.values)
        ? record.values as Record<string, unknown>
        : {},
    ),
    createdAt: normalizeTimestamp(record.createdAt),
    updatedAt: normalizeTimestamp(record.updatedAt),
  };
}

function normalizeProfileValues(values: Record<string, unknown>): Record<string, string> {
  const normalized: Record<string, string> = {};
  for (const field of MODEL_PROFILE_FIELDS) {
    normalized[field.key] = String(values[field.key] ?? "");
  }
  return normalized;
}

function normalizeProfileStorageValues(values: Record<string, unknown>): Record<string, string> {
  const normalized = normalizeProfileValues(values);
  for (const field of MODEL_PROFILE_SECRET_FIELDS) {
    delete normalized[field.key];
  }
  return normalized;
}

function hydrateModelProfileSecrets(
  config: readonly ConsoleConfigEntry[],
  uid: number,
  profile: ConsoleModelProfile,
): ConsoleModelProfile {
  const values = { ...profile.values };
  for (const field of MODEL_PROFILE_SECRET_FIELDS) {
    const secret = configValueForKey(config, modelProfileSecretConfigKey(uid, profile.id, field.key));
    if (secret) {
      values[field.key] = secret;
    }
  }
  return { ...profile, values };
}

function redactModelProfileSecrets(profile: unknown): unknown {
  if (!profile || typeof profile !== "object" || Array.isArray(profile)) {
    return profile;
  }
  const record = profile as Record<string, unknown>;
  if (!record.values || typeof record.values !== "object" || Array.isArray(record.values)) {
    return record;
  }
  const values = { ...(record.values as Record<string, unknown>) };
  for (const key of Object.keys(values)) {
    if (isSensitiveSettingKey(key)) {
      values[key] = "";
    }
  }
  return { ...record, values };
}

function normalizeProfileName(value: unknown): string {
  return String(value ?? "").trim().replace(/\s+/g, " ").slice(0, MAX_PROFILE_NAME_LENGTH);
}

function normalizeProfileId(value: unknown): string {
  return String(value ?? "").trim().toLowerCase().replace(/[^a-z0-9_-]/g, "");
}

function normalizeTimestamp(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : Date.now();
}

function uniqueProfileId(profiles: readonly ConsoleModelProfile[], name: string): string {
  const used = new Set(profiles.map((profile) => profile.id));
  const base = slugify(name) || "profile";
  let candidate = base;
  let suffix = 2;
  while (used.has(candidate)) {
    candidate = `${base}-${suffix}`;
    suffix += 1;
  }
  return candidate;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
}

function cleanValue(value: unknown): string {
  return String(value ?? "").trim();
}
