/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 58b71f7341bfa02fcf9854b1426b6602)
interface __BaseEnv_Env {
	ACCOUNT_DB: D1Database;
	ENVIRONMENT: "production";
	GSV_ACCOUNT_ORIGIN: "https://gsv.space";
	GSV_BASE_DOMAIN: "gsv.space";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "GSV_ACCOUNT_ORIGIN" | "GSV_BASE_DOMAIN">> {}
}
