/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 74c6bbc2ae20f332a15d178854da92d5)
interface __BaseEnv_Env {
	ACCOUNT_DB: D1Database;
	ENVIRONMENT: "production";
	GSV_ACCOUNT_ORIGIN: "https://gsv.space";
	GSV_BASE_DOMAIN: "gsv.space";
	GSV_ADMIN_ACCESS_TEAM_DOMAIN: string;
	GSV_ADMIN_ACCESS_AUD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "GSV_ACCOUNT_ORIGIN" | "GSV_BASE_DOMAIN" | "GSV_ADMIN_ACCESS_TEAM_DOMAIN" | "GSV_ADMIN_ACCESS_AUD">> {}
}
