/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bb5c4a8713d1d74b1ddc863cea2e989a)
interface __BaseEnv_Env {
	ACCOUNT_DB: D1Database;
	GSV_BASE_DOMAIN: "gsv.space";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GSV_BASE_DOMAIN">> {}
}
