import type { SyscallName } from "@humansandmachines/gsv/protocol";

/** Every protocol operation has a plain-language label; new operations must supply one. */
const labels = {
  "fs.read": "read a file",
  "fs.write": "wrote a file",
  "fs.edit": "edited a file",
  "fs.delete": "removed a file",
  "fs.search": "searched files",
  "fs.copy": "copied a file",
  "fs.transfer.stat": "checked a file transfer",
  "fs.transfer.send": "sent a file to another place",
  "fs.transfer.receive": "received a file from another place",
  "shell.exec": "ran a command",
  "net.fetch": "fetched from the web",
  "codemode.exec": "ran a script",
  "codemode.run": "ran a script",
  "mail.send": "sent an email",
  "mail.status": "checked email delivery",
  "conversation.ship": "opened Ship",
  "conversation.forProcess": "found a process conversation",
  "conversation.list": "listed conversations",
  "conversation.history": "read a conversation",
  "conversation.send": "sent a message",
  "conversation.media.read": "opened a message attachment",
  "contact.identity": "checked contact identity",
  "contact.invite.create": "created a contact invitation",
  "contact.invite.accept": "accepted a contact invitation",
  "contact.invite.list": "listed contact invitations",
  "contact.invite.cancel": "cancelled a contact invitation",
  "contact.list": "listed contacts",
  "contact.alias.set": "renamed a contact",
  "contact.revoke": "disconnected a contact",
  "contact.send": "sent a message to a contact",
  "contact.delivery.get": "checked contact delivery",
  "contact.request.list": "listed contact requests",
  "contact.request.create": "created a contact request",
  "contact.request.update": "updated a contact request",
  "proc.spawn": "started a helper",
  "proc.kill": "ended a process",
  "proc.list": "listed processes",
  "proc.observe": "started watching a process",
  "proc.unobserve": "stopped watching a process",
  "proc.send": "sent input to a process",
  "proc.ipc.send": "sent a message to a process",
  "proc.ipc.call": "asked a process for a result",
  "proc.ipc.deliver": "delivered a process result",
  "proc.abort": "stopped a run",
  "proc.hil": "answered an approval request",
  "proc.history": "read process history",
  "proc.trace": "read a process trace",
  "proc.history.policy.get": "read history settings",
  "proc.history.policy.set": "changed history settings",
  "proc.history.compact": "compacted process history",
  "proc.history.export": "exported process history",
  "proc.history.import": "imported process history",
  "proc.history.segment.read": "read archived process history",
  "proc.history.segments": "listed history archives",
  "proc.fork": "forked a process",
  "proc.ai.config.get": "read process model settings",
  "proc.ai.config.set": "changed process model settings",
  "proc.reset": "reset a process",
  "proc.setidentity": "changed process identity",
  "repo.list": "listed repositories",
  "repo.create": "created a repository",
  "repo.refs": "listed branches and tags",
  "repo.read": "read a repository",
  "repo.search": "searched a repository",
  "repo.log": "read repository history",
  "repo.diff": "checked repository changes",
  "repo.compare": "compared repository versions",
  "repo.apply": "applied repository changes",
  "repo.import": "imported a repository",
  "repo.delete": "deleted a repository",
  "repo.visibility.set": "changed repository visibility",
  "sys.connect": "connected to the gateway",
  "sys.setup.assist": "checked setup options",
  "sys.setup": "set up an installation",
  "sys.bootstrap": "prepared the cloud home",
  "sys.config.get": "read settings",
  "sys.config.set": "changed a setting",
  "sys.target.list": "listed places",
  "sys.target.get": "checked a place",
  "sys.target.update": "updated a place",
  "sys.target.delete": "forgot a place",
  "sys.ledger.list": "read the ledger",
  "sys.oauth.start": "started provider sign-in",
  "sys.oauth.device.start": "started provider sign-in",
  "sys.oauth.device.poll": "checked provider sign-in",
  "sys.oauth.list": "listed provider connections",
  "sys.oauth.forget": "disconnected a provider",
  "sys.mcp.add": "connected a tool server",
  "sys.mcp.list": "listed tool servers",
  "sys.mcp.remove": "disconnected a tool server",
  "sys.mcp.refresh": "refreshed a tool server",
  "sys.mcp.call": "used a connected tool",
  "sys.token.create": "created an access key",
  "sys.token.list": "listed access keys",
  "sys.token.revoke": "revoked an access key",
  "sys.link": "linked a messaging identity",
  "sys.unlink": "unlinked a messaging identity",
  "sys.link.list": "listed messaging identities",
  "sys.link.consume": "confirmed a messaging link",
  "account.create": "created an account",
  "account.list": "listed accounts",
  "sched.list": "listed schedules",
  "sched.add": "created a schedule",
  "sched.update": "updated a schedule",
  "sched.remove": "removed a schedule",
  "sched.run": "ran scheduled work",
  "r12y.list": "listed responsibilities",
  "r12y.get": "read a responsibility",
  "r12y.create": "created a responsibility",
  "r12y.update": "updated a responsibility",
  "r12y.changes": "read responsibility changes",
  "r12y.source.list": "listed responsibility sources",
  "r12y.source.update": "updated a responsibility source",
  "ai.tools": "listed available tools",
  "ai.context": "read agent context",
  "ai.config": "read model settings",
  "ai.models": "listed models",
  "ai.text.generate": "generated text",
  "ai.transcription.create": "transcribed audio",
  "ai.image.read": "read an image",
  "ai.image.generate": "generated an image",
  "ai.speech.create": "generated speech",
  "adapter.connect": "connected a messenger",
  "adapter.disconnect": "disconnected a messenger",
  "adapter.inbound": "received a message",
  "adapter.state.update": "updated messenger state",
  "adapter.send": "sent a message",
  "adapter.status": "checked a messenger",
  "adapter.list": "listed messengers",
  "adapter.pair.info": "checked messenger setup",
  "adapter.pair.inspect": "checked a messenger connection",
  "adapter.pair.confirm": "confirmed a messenger connection",
  "adapter.pair.disconnect": "unpaired a messenger",
  "signal.watch": "started watching events",
  "signal.unwatch": "stopped watching events",
} satisfies Record<SyscallName, string>;

export function ledgerLabel(syscall: string): string {
  // SAFETY: labels is checked against every SyscallName; hasOwn proves this key belongs to it.
  return Object.hasOwn(labels, syscall) ? labels[syscall as SyscallName] : "used another capability";
}
