import {
  APP_RUNTIME_BACKEND_COMPATIBILITY_DATE,
  APP_RUNTIME_BACKEND_COMPATIBILITY_FLAGS,
} from "./backend";

type AppBackendNetworkPolicy = "none" | "gateway";

type BuiltinAppBackendFactory = {
  moduleCode: string;
};

const BUILTIN_APP_BACKENDS: Record<string, BuiltinAppBackendFactory> = {
  "workspace-doctor-backend": {
    moduleCode: [
      'import { WorkerEntrypoint } from "cloudflare:workers";',
      "",
      "function formatBindings(bindings) {",
      "  if (!Array.isArray(bindings) || bindings.length === 0) {",
      '    return "none";',
      "  }",
      "",
      "  return bindings.map((binding) => {",
      '    if (binding.kind === "kernel") {',
      '      return `kernel:${binding.syscalls.join(",")}`;',
      "    }",
      '    if (binding.kind === "workspace") {',
      '      return `workspace:${binding.access}:${binding.workspace.workspaceId}`;',
      "    }",
      '    if (binding.kind === "thread") {',
      '      return `thread:${binding.thread.pid}`;',
      "    }",
      '    if (binding.kind === "service") {',
      '      return `service:${binding.binding}:${binding.status}`;',
      "    }",
      '    return binding.kind ?? "unknown";',
      '  }).join("\\n");',
      "}",
      "",
      "function resolveTarget(argv, session) {",
      '  const target = typeof argv[1] === "string" && argv[1].trim()',
      "    ? argv[1].trim()",
      '    : session.workspace?.cwd ?? session.workspace?.root ?? ".";',
      "  return target;",
      "}",
      "",
      "function formatSessionSummary(session, target) {",
      '  const workspaceId = session.workspace?.workspaceId ?? "none";',
      '  const cwd = session.workspace?.cwd ?? session.thread?.cwd ?? "none";',
      '  return [',
      '    "workspace-doctor backend online",',
      '    `session: ${session.sessionId}`,',
      '    `host: ${session.host.kind}:${session.host.instanceId}`,',
      '    `surface: ${session.surface.kind}:${session.surface.name}`,',
      '    `workspace: ${workspaceId}`,',
      '    `cwd: ${cwd}`,',
      '    `target: ${target}`,',
      '    "bindings:",',
      "    formatBindings(session.backend?.bindings ?? []),",
      '  ].join("\\n");',
      "}",
      "",
      "function summarizeReadResult(result) {",
      "  if (!result || result.ok !== true) {",
      '    return `error: ${result?.error ?? "unknown"}`;',
      "  }",
      "",
      "  if (Array.isArray(result.files) || Array.isArray(result.directories)) {",
      "    const directories = Array.isArray(result.directories) ? result.directories : [];",
      "    const files = Array.isArray(result.files) ? result.files : [];",
      "    const entries = [",
      '      ...directories.map((entry) => `${entry}/`),',
      "      ...files,",
      "    ].slice(0, 8);",
      "    return entries.length > 0",
      '      ? `directory entries: ${entries.join(", ")}`',
      '      : "directory entries: (empty)";',
      "  }",
      "",
      '  return `file bytes: ${result.size ?? 0}`;',
      "}",
      "",
      "function summarizeShellExec(result) {",
      "  if (!result || result.ok !== true) {",
      '    return `error: ${result?.error ?? "unknown"}`;',
      "  }",
      "",
      '  const stdout = typeof result.stdout === "string" ? result.stdout.trim() : "";',
      "  return stdout || `(exit ${result.exitCode ?? 0})`;",
      "}",
      "",
      "export class WorkspaceDoctor extends WorkerEntrypoint {",
      "  async execCommand(input) {",
      "    const session = this.ctx.props?.session;",
      "    if (!session) {",
      '      return { stdout: "", stderr: "doctor: backend session context is missing\\n", exitCode: 1 };',
      "    }",
      "",
      "    const argv = Array.isArray(input?.command?.argv) ? input.command.argv : [];",
      '    const subcommand = typeof argv[0] === "string" && argv[0].trim() ? argv[0].trim() : "scan";',
      "    const target = resolveTarget(argv, session);",
      "",
      '    if (subcommand === "scan") {',
      "      if (!session.workspace) {",
      '        return { stdout: "", stderr: "doctor: no workspace is attached to this session\\n", exitCode: 1 };',
      "      }",
      "",
      "      const kernel = this.env.KERNEL;",
      "      if (!kernel || typeof kernel.call !== \"function\") {",
      '        return { stdout: "", stderr: "doctor: KERNEL binding is not available\\n", exitCode: 1 };',
      "      }",
      "",
      "      try {",
      "        const inspectedPath = await kernel.call(\"fs.read\", { path: target });",
      "        const workspaceMeta = await kernel.call(\"fs.read\", {",
      "          path: `${session.workspace.root}/.gsv/workspace.json`,",
      "        });",
      "        const pwd = await kernel.call(\"shell.exec\", {",
      '          command: "pwd",',
      "          workdir: session.workspace.cwd,",
      "          timeout: 5000,",
      "        });",
      "",
      "        return {",
      '          stdout: [',
      "            formatSessionSummary(session, target),",
      '            `inspect: ${summarizeReadResult(inspectedPath)}` ,',
      '            `workspace metadata: ${workspaceMeta.ok ? "present" : `missing (${workspaceMeta.error ?? "unknown"})`}` ,',
      '            `shell pwd: ${summarizeShellExec(pwd)}` ,',
      '            "status: kernel binding active",',
      '          ].join("\\n") + "\\n",',
      '          stderr: "",',
      "          exitCode: 0,",
      "        };",
      "      } catch (error) {",
      '        return { stdout: "", stderr: `doctor: scan failed: ${error instanceof Error ? error.message : String(error)}\\n`, exitCode: 1 };',
      "      }",
      "    }",
      "",
      '    if (subcommand === "explain") {',
      "      return {",
      '        stdout: `doctor explain\\n${formatSessionSummary(session, target)}\\nnext: use declared kernel bindings to inspect files and shell state\\n`,',
      '        stderr: "",',
      "        exitCode: 0,",
      "      };",
      "    }",
      "",
      '    if (subcommand === "fix") {',
      "      return {",
      '        stdout: `doctor fix\\nworkspace: ${session.workspace?.workspaceId ?? "none"}\\ntarget: ${target}\\nstatus: fix planner scaffolded; no mutations executed yet\\n`,',
      '        stderr: "",',
      "        exitCode: 0,",
      "      };",
      "    }",
      "",
      "    return {",
      '      stdout: "",',
      '      stderr: `doctor: unknown subcommand "${subcommand}"\\n`,',
      "      exitCode: 2,",
      "    };",
      "  }",
      "}",
      "",
    ].join("\n"),
  },
  "ops-console-backend": {
    moduleCode: [
      'import { WorkerEntrypoint } from "cloudflare:workers";',
      "",
      "export class OpsConsole extends WorkerEntrypoint {",
      "  async describeSession() {",
      "    const session = this.ctx.props?.session;",
      "    return {",
      '      appId: session?.appId ?? "ops-console",',
      '      host: session?.host ?? null,',
      '      surface: session?.surface ?? null,',
      '      workspace: session?.workspace ?? null,',
      "    };",
      "  }",
      "}",
      "",
    ].join("\n"),
  },
  "deploy-backend": {
    moduleCode: [
      'import { WorkerEntrypoint } from "cloudflare:workers";',
      "",
      "function supportedSubcommand(name) {",
      '  return ["up", "status", "logs", "rollback"].includes(name);',
      "}",
      "",
      "export class DeployControlPlane extends WorkerEntrypoint {",
      "  async execCommand(input) {",
      "    const session = this.ctx.props?.session;",
      "    if (!session) {",
      '      return { stdout: "", stderr: "deploy: backend session context is missing\\n", exitCode: 1 };',
      "    }",
      "",
      "    const argv = Array.isArray(input?.command?.argv) ? input.command.argv : [];",
      '    const subcommand = typeof argv[0] === "string" && argv[0].trim() ? argv[0].trim() : "status";',
      "",
      "    if (!supportedSubcommand(subcommand)) {",
      "      return {",
      '        stdout: "",',
      '        stderr: `deploy: unknown subcommand "${subcommand}"\\n`,',
      "        exitCode: 2,",
      "      };",
      "    }",
      "",
      "    return {",
      '      stdout: [',
      '        `deploy ${subcommand}` ,',
      '        "deploy backend online",',
      '        `session: ${session.sessionId}`,',
      '        `host: ${session.host.kind}:${session.host.instanceId}`,',
      '        `workspace: ${session.workspace?.workspaceId ?? "none"}`,',
      '        "status: command scaffolded; provider actions not wired yet",',
      '      ].join("\\n") + "\\n",',
      '      stderr: "",',
      "      exitCode: 0,",
      "    };",
      "  }",
      "}",
      "",
    ].join("\n"),
  },
};

export function getBuiltinAppBackendWorkerCode(
  workerName: string,
  network: AppBackendNetworkPolicy,
): WorkerLoaderWorkerCode | null {
  const backend = BUILTIN_APP_BACKENDS[workerName];
  if (!backend) {
    return null;
  }

  return {
    compatibilityDate: APP_RUNTIME_BACKEND_COMPATIBILITY_DATE,
    compatibilityFlags: [...APP_RUNTIME_BACKEND_COMPATIBILITY_FLAGS],
    mainModule: "index.js",
    modules: {
      "index.js": {
        js: backend.moduleCode,
      },
    },
    ...(network === "none" ? { globalOutbound: null } : {}),
  };
}
