import type { SqlMigration } from "../../schema/runner";

export const KERNEL_V059_FIRST_CONTACT_REQUESTS: SqlMigration = {
  id: 59,
  name: "first_contact_requests",
  statements: [
    `CREATE TABLE social_approaches (
      approach_id TEXT PRIMARY KEY,
      owner_uid INTEGER NOT NULL,
      direction TEXT NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
      origin_ship_id TEXT NOT NULL,
      origin_subject_id TEXT NOT NULL,
      origin_id TEXT NOT NULL,
      remote_ship_id TEXT NOT NULL,
      remote_subject_id TEXT NOT NULL,
      remote_origin TEXT NOT NULL,
      remote_public_key_json TEXT NOT NULL,
      remote_display_name TEXT NOT NULL,
      local_display_name TEXT NOT NULL,
      conversation_id TEXT NOT NULL,
      contact_id TEXT NOT NULL,
      thread_id TEXT NOT NULL,
      state TEXT NOT NULL CHECK (state IN ('preparing', 'pending', 'accepting', 'accepted', 'declined', 'withdrawn', 'expired', 'blocked')),
      revision INTEGER NOT NULL DEFAULT 1,
      fingerprint TEXT NOT NULL,
      idempotency_key TEXT,
      metadata_json TEXT NOT NULL,
      pending_text TEXT,
      pending_text_bytes INTEGER NOT NULL DEFAULT 0,
      message_sequence INTEGER,
      setup_token TEXT,
      setup_token_hash TEXT NOT NULL UNIQUE,
      setup_invite_id TEXT,
      pairing_attempt_id TEXT,
      contact_generation TEXT,
      claim_receipt_json TEXT,
      delivery_state TEXT NOT NULL CHECK (delivery_state IN ('queued', 'received', 'failed', 'unconfirmed')),
      attempts INTEGER NOT NULL DEFAULT 0,
      next_attempt_at INTEGER,
      accepted_at INTEGER,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      expires_at INTEGER NOT NULL,
      cleanup_at INTEGER,
      UNIQUE (owner_uid, origin_ship_id, origin_subject_id, origin_id),
      UNIQUE (owner_uid, idempotency_key)
    )`,
    `CREATE UNIQUE INDEX social_approaches_unresolved_peer ON social_approaches (owner_uid, remote_ship_id, remote_subject_id)
      WHERE state IN ('preparing', 'pending', 'accepting')`,
    "CREATE INDEX social_approaches_inbox ON social_approaches (owner_uid, direction, created_at DESC, approach_id DESC)",
    "CREATE INDEX social_approaches_cleanup ON social_approaches (cleanup_at) WHERE cleanup_at IS NOT NULL",
    "CREATE INDEX social_approaches_expiry ON social_approaches (expires_at) WHERE state IN ('preparing', 'pending')",
    "CREATE INDEX social_approaches_recovery ON social_approaches (next_attempt_at) WHERE next_attempt_at IS NOT NULL",
    "CREATE UNIQUE INDEX social_approaches_invite ON social_approaches (setup_invite_id) WHERE setup_invite_id IS NOT NULL",
  ],
};
