/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c42df9837675be3b5cb03326ca9481b0)
interface __BaseEnv_Env {
	INSTALLATIONS_DB: D1Database;
	GSV_BASE_DOMAIN: "example.com";
	ENVIRONMENT: "production";
	GSV_ADMIN_ORIGIN: "https://accounts.example.com";
	GSV_ADMIN_ACCESS_TEAM_DOMAIN: "";
	GSV_ADMIN_ACCESS_AUD: "";
	GSV_OWNER_OIDC_ISSUER: "";
	GSV_OWNER_OIDC_CLIENT_ID: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GSV_BASE_DOMAIN" | "ENVIRONMENT" | "GSV_ADMIN_ORIGIN" | "GSV_ADMIN_ACCESS_TEAM_DOMAIN" | "GSV_ADMIN_ACCESS_AUD" | "GSV_OWNER_OIDC_ISSUER" | "GSV_OWNER_OIDC_CLIENT_ID">> {}
}
