/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cbb705fcdb9ab684542fc4961a128ed3)
interface __BaseEnv_Env {
	INSTALLATIONS_DB: D1Database;
	GSV_BASE_DOMAIN: "example.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GSV_BASE_DOMAIN">> {}
}
