/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: da00440b0d9bbc6975d284703bf4ca3a)
interface __BaseEnv_Env {
	STORAGE: R2Bucket;
	LOADER: WorkerLoader;
	AI: Ai;
	ASSETS: Fetcher;
	KERNEL: DurableObjectNamespace<import("./src/index").Kernel>;
	PROCESS: DurableObjectNamespace<import("./src/index").Process>;
	CONVERSATION: DurableObjectNamespace<import("./src/index").Conversation>;
	CHANNEL_TELEGRAM: Service /* entrypoint TelegramChannel from gsv-channel-telegram */;
	CHANNEL_DISCORD: Service /* entrypoint DiscordChannel from gsv-channel-discord */;
	CHANNEL_WHATSAPP: Service /* entrypoint WhatsAppChannelEntrypoint from gsv-channel-whatsapp */;
	RIPGIT: Fetcher /* ripgit */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Kernel" | "Process" | "Conversation";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.md" {
	const value: string;
	export default value;
}
