export type {
  AdapterAccountStatus,
  AdapterActivity,
  AdapterActor,
  AdapterConnectConfig,
  AdapterConnectResult,
  AdapterDisconnectResult,
  AdapterInboundMessage,
  AdapterInboundResult,
  AdapterInstallationContext,
  AdapterMedia,
  AdapterOutboundMessage,
  AdapterPairingActivateInput,
  AdapterPairingCandidate,
  AdapterPairingDisconnectInput,
  AdapterPairingDisconnectResult,
  AdapterPairingFinalizeInput,
  AdapterPairingInfo,
  AdapterPairingPreparation,
  AdapterPairingPrepareInput,
  AdapterPairingRoute,
  AdapterSendResult,
  AdapterService,
  AdapterServiceDescriptor,
  AdapterSurface,
  BinaryBody,
} from "../../shared/src/types";
