// Generated by tools/protocol/generate-host-protocol-types.mjs from
// packages/gsv/src/protocol. Do not edit by hand; run npm run protocol:generate.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Structured failure carried by an error response on every carrier.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErrorShape {
    pub code: i32,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retryable: Option<bool>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FrameBodyDescriptor {
    pub stream_id: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub length: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProcessIdentity {
    pub uid: u64,
    pub gid: u64,
    pub gids: Vec<u64>,
    pub username: String,
    pub home: String,
    pub cwd: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PeerPrincipalKind {
    #[serde(rename = "human")]
    Human,
    #[serde(rename = "machine")]
    Machine,
    #[serde(rename = "service")]
    Service,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PeerPrincipal {
    pub kind: PeerPrincipalKind,
    pub account: ProcessIdentity,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PeerGrant {
    /// Syscall patterns this peer may invoke.
    pub calls: Vec<String>,
    /// Signal names this peer may receive.
    pub signals: Vec<String>,
    /// Syscall patterns this peer implements for GSV.
    pub implements: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConnectedPeer {
    /// Application/device/service identity chosen by the peer. Routeable endpoints keep it stable.
    pub id: String,
    /// One live authenticated connection incarnation, assigned by the Kernel.
    pub session_id: String,
    pub principal: PeerPrincipal,
    pub grant: PeerGrant,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConnectArgs {
    pub protocol: u32,
    pub peer: PeerInfo,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth: Option<AuthInfo>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PeerInfo {
    pub id: String,
    pub version: String,
    pub platform: String,
    /// Requested reverse syscall implementations. Authority is server-derived.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub implements: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthInfo {
    pub username: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConnectResult {
    pub protocol: u32,
    pub server: ServerInfo,
    pub peer: ConnectedPeer,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerInfo {
    pub connection_id: String,
    pub version: String,
    pub release: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub features: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolDefinition {
    pub name: String,
    pub description: String,
    pub input_schema: Value,
}
