/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9064621b8d022380129340145f0f8055)
interface __BaseEnv_Env {
	AI: Ai;
	INFERENCE_DEFAULT_PROVIDER: "workers-ai";
	INFERENCE_DEFAULT_MODEL: "@cf/zai-org/glm-5.3-flash";
	INFERENCE_MONTHLY_REQUESTS: 10000;
	INFERENCE_MONTHLY_OUTPUT_TOKENS: 1000000;
	INFERENCE_MAX_OUTPUT_TOKENS: 32768;
	INFERENCE_MAX_DURATION_MS: 180000;
	INFERENCE_EXECUTORS: DurableObjectNamespace<import("./src/index").InferenceExecutor>;
	INSTALLATION_DIRECTORY: Fetcher /* gsv-installations */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "InferenceExecutor";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INFERENCE_DEFAULT_PROVIDER" | "INFERENCE_DEFAULT_MODEL" | "INFERENCE_MONTHLY_REQUESTS" | "INFERENCE_MONTHLY_OUTPUT_TOKENS" | "INFERENCE_MAX_OUTPUT_TOKENS" | "INFERENCE_MAX_DURATION_MS">> {}
}
