/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5bbec14105e64a994076b716c19a1178)
interface __BaseEnv_Env {
	WHATSAPP_ACCOUNT: DurableObjectNamespace<import("./src/index").WhatsAppAccount>;
	GATEWAY: Service /* entrypoint AdapterGatewayEntrypoint from gsv */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WhatsAppAccount";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
