/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c74dbcbc785ee6cdf550399389c91e2b)
interface __BaseEnv_Env {
	WHATSAPP_ACCOUNT: DurableObjectNamespace<import("./src/index").WhatsAppAccount>;
	GATEWAY: Service /* entrypoint GatewayEntrypoint from gsv */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WhatsAppAccount";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
