/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1071b0a0bc6a844cf0e1fbd88eb8aa60)
interface __BaseEnv_Env {
	STORAGE: R2Bucket;
	LOADER: WorkerLoader;
	ASSETS: Fetcher;
	KERNEL: DurableObjectNamespace<import("./src/index").Kernel>;
	PROCESS: DurableObjectNamespace<import("./src/index").Process>;
	CONVERSATION: DurableObjectNamespace<import("./src/index").Conversation>;
	INSTALLATION_DIRECTORY: Fetcher /* gsv-installations */;
	INSTALLATION_OWNERSHIP: Service /* entrypoint InstallationOwnershipEntrypoint from gsv-installations */;
	INFERENCE_EXECUTION: Fetcher /* gsv-inference */;
	RIPGIT: Fetcher /* ripgit */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Kernel" | "Process" | "Conversation";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.md" {
	const value: string;
	export default value;
}