export type {
  AdapterAccountStatus,
  AdapterActivity,
  AdapterActor,
  AdapterCapabilities,
  AdapterConnectChallenge,
  AdapterConnectResult,
  AdapterDisconnectResult,
  AdapterInboundMessage,
  AdapterInboundResult,
  AdapterMedia,
  AdapterOutboundMessage,
  AdapterSendResult,
  AdapterSurface,
  AdapterSurfaceKind,
  AdapterWorkerInterface,
  GatewayFrame,
  GatewayRequestFrame,
  GatewayResponseFrame,
  ShellExecArgs,
  ShellExecResult,
} from "../../shared/src/types";
