/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 2017c07abb0067c3baffc76fac16caeb)
interface __BaseEnv_Env {
	TEST_CHANNEL_STATE: DurableObjectNamespace<import("./src/index").TestChannelState>;
	GATEWAY: Service /* entrypoint AdapterGatewayEntrypoint from gsv */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "TestChannelState";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
