name = "assembler-rs"
main = "build/index.js"
compatibility_date = "2026-04-22"
workers_dev = false

[build]
command = "cargo install -q \"worker-build@^0.7\" && worker-build --release"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
