/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.shared.jsonc --include-runtime=false` (hash: 90e956715fbacbbc024e0aacd7c82e71)
interface __BaseEnv_Env {
	DISCORD_GATEWAY: DurableObjectNamespace<import("./src/shared").DiscordGateway>;
	DISCORD_APPLICATION: DurableObjectNamespace<import("./src/shared").DiscordApplication>;
	DISCORD_PEER: DurableObjectNamespace<import("./src/shared").DiscordPeer>;
	DISCORD_PAIRING: DurableObjectNamespace<import("./src/shared").DiscordPairing>;
	DISCORD_INSTALLATIONS: DurableObjectNamespace<import("./src/shared").DiscordInstallation>;
	GATEWAY: Service /* entrypoint AdapterGatewayEntrypoint from gsv */;
	ACCOUNTS: Fetcher /* gsv-installations */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/shared");
		durableNamespaces: "DiscordGateway" | "DiscordApplication" | "DiscordPeer" | "DiscordPairing" | "DiscordInstallation";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
