/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: e607da3fa455ddd6910ad48ca491b976)
interface __BaseEnv_Env {
	DISCORD_GATEWAY: DurableObjectNamespace<import("./src/index").DiscordGateway>;
	GATEWAY: Service /* entrypoint AdapterGatewayEntrypoint from gsv */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DiscordGateway";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
