import type { SettingField } from "./types";

export const AI_FIELDS: SettingField[] = [
  {
    key: "config/ai/provider",
    label: "Chat provider",
    description: "LLM provider used for system-owned runs and default inference routing.",
    kind: "text",
    placeholder: "workers-ai",
  },
  {
    key: "config/ai/model",
    label: "Chat model",
    description: "Model identifier passed to the selected provider.",
    kind: "text",
    placeholder: "@cf/nvidia/nemotron-3-120b-a12b",
  },
  {
    key: "config/ai/api_key",
    label: "API key",
    description: "Provider API key. Leave empty for local or built-in providers when valid.",
    kind: "password",
  },
  {
    key: "config/ai/reasoning",
    label: "Reasoning mode",
    description: "Reasoning effort hint for models that support extended thinking.",
    kind: "select",
    options: [
      { value: "off", label: "Off" },
      { value: "minimal", label: "Minimal" },
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
      { value: "xhigh", label: "Extra High" },
    ],
  },
  {
    key: "config/ai/max_tokens",
    label: "Max tokens",
    description: "Upper bound for generated response size.",
    kind: "number",
  },
  {
    key: "config/ai/max_context_bytes",
    label: "Max context bytes",
    description: "Maximum bytes of home context injected into prompts.",
    kind: "number",
  },
  {
    key: "config/ai/image/read/provider",
    label: "Image reader provider",
    description: "Provider used to describe images. workers-ai uses the binding; other providers route through pi-ai.",
    kind: "text",
    placeholder: "workers-ai",
  },
  {
    key: "config/ai/image/read/model",
    label: "Image reader model",
    description: "Vision model used to generate text descriptions for attached images.",
    kind: "text",
    placeholder: "@cf/google/gemma-4-26b-a4b-it",
  },
  {
    key: "config/ai/image/read/api_key",
    label: "Image reader API key",
    description: "Optional credential for the image reader provider. Falls back to the chat API key when empty.",
    kind: "password",
  },
  {
    key: "config/ai/image/read/input_format",
    label: "Image reader input",
    description: "Workers AI binding request shape. Other providers use native pi-ai image content.",
    kind: "select",
    options: [
      { value: "auto", label: "Auto" },
      { value: "chat", label: "Chat vision" },
      { value: "image", label: "Raw image" },
    ],
  },
  {
    key: "config/ai/image/read/max_bytes",
    label: "Image reader max bytes",
    description: "Maximum stored image size sent to the image-reading model.",
    kind: "number",
  },
  {
    key: "config/ai/image/read/max_tokens",
    label: "Image reader tokens",
    description: "Maximum text tokens generated by the image-reading model.",
    kind: "number",
  },
  {
    key: "config/ai/image/read/timeout_ms",
    label: "Image reader timeout",
    description: "Maximum time to wait for image description generation.",
    kind: "number",
  },
  {
    key: "config/ai/image/read/prompt",
    label: "Image reader prompt",
    description: "Instruction used when converting images into text context.",
    kind: "textarea",
    rows: 3,
  },
  {
    key: "config/ai/image/generation/provider",
    label: "Image generator provider",
    description: "Provider reserved for text-to-image and image-editing capabilities.",
    kind: "text",
    placeholder: "workers-ai",
  },
  {
    key: "config/ai/image/generation/model",
    label: "Image generator model",
    description: "Default model for image generation.",
    kind: "text",
    placeholder: "@cf/black-forest-labs/flux-1-schnell",
  },
  {
    key: "config/ai/image/generation/api_key",
    label: "Image generator API key",
    description: "Optional credential for the image generator provider. Falls back to the chat API key when empty.",
    kind: "password",
  },
  {
    key: "config/ai/transcription/provider",
    label: "Transcription provider",
    description: "Provider used by audio attachments and ai.transcription.create.",
    kind: "text",
    placeholder: "workers-ai",
  },
  {
    key: "config/ai/transcription/model",
    label: "Transcription model",
    description: "Speech-to-text model used by audio attachments and ai.transcription.create.",
    kind: "text",
    placeholder: "@cf/openai/whisper-large-v3-turbo",
  },
  {
    key: "config/ai/transcription/max_bytes",
    label: "Transcription max bytes",
    description: "Maximum audio payload size accepted for transcription.",
    kind: "number",
  },
  {
    key: "config/ai/transcription/api_key",
    label: "Transcription API key",
    description: "Optional credential for the transcription provider. Falls back to the chat API key when empty.",
    kind: "password",
  },
  {
    key: "config/ai/speech/provider",
    label: "Speech provider",
    description: "Provider used by ai.speech.create.",
    kind: "text",
    placeholder: "workers-ai",
  },
  {
    key: "config/ai/speech/model",
    label: "Speech model",
    description: "Text-to-speech model used by ai.speech.create.",
    kind: "text",
    placeholder: "@cf/deepgram/aura-2-en",
  },
  {
    key: "config/ai/speech/api_key",
    label: "Speech API key",
    description: "Optional credential for the speech provider. Falls back to the chat API key when empty.",
    kind: "password",
  },
  {
    key: "config/ai/speech/speaker",
    label: "Speech speaker",
    description: "Default voice or speaker for speech synthesis.",
    kind: "text",
    placeholder: "luna",
  },
  {
    key: "config/ai/speech/encoding",
    label: "Speech encoding",
    description: "Default audio encoding for synthesized speech.",
    kind: "text",
    placeholder: "mp3",
  },
  {
    key: "config/ai/speech/max_chars",
    label: "Speech max chars",
    description: "Maximum normalized text length accepted for speech synthesis.",
    kind: "number",
  },
  {
    key: "config/ai/speech/timeout_ms",
    label: "Speech timeout",
    description: "Maximum time to wait for speech synthesis.",
    kind: "number",
  },
];

export const SHELL_FIELDS: SettingField[] = [
  {
    key: "config/shell/timeout_ms",
    label: "Timeout (ms)",
    description: "Default timeout for native shell execution.",
    kind: "number",
  },
  {
    key: "config/shell/network_enabled",
    label: "Network enabled",
    description: "Allow network-capable shell tools such as curl and wget.",
    kind: "checkbox",
  },
  {
    key: "config/shell/max_output_bytes",
    label: "Max output bytes",
    description: "Maximum captured shell output before truncation.",
    kind: "number",
  },
];

export const SERVER_FIELDS: SettingField[] = [
  {
    key: "config/server/name",
    label: "Instance name",
    description: "Human-readable name shown by system tools and shell surfaces.",
    kind: "text",
  },
  {
    key: "config/server/timezone",
    label: "Timezone",
    description: "IANA timezone used for scheduling and timestamps.",
    kind: "text",
    placeholder: "Europe/Amsterdam",
  },
  {
    key: "config/server/version",
    label: "Version",
    description: "Current server version reported by the runtime.",
    kind: "readonly",
  },
];

export function buildUserAiOverrideKey(uid: number, systemKey: string): string {
  if (!systemKey.startsWith("config/ai/")) {
    throw new Error(`Cannot build user AI override for non-AI key: ${systemKey}`);
  }
  return `users/${uid}/${systemKey.slice("config/".length)}`;
}
