/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e541ed97c09c0d92cd714d0ee8a74870)
interface __BaseEnv_Env {
	MAIL_DOMAIN: "gsv.space";
	GSV_BASE_DOMAIN: "gsv.space";
	MAIL_MAX_MESSAGE_BYTES: 16777216;
	MAIL_DAILY_INBOUND_MESSAGE_LIMIT: 250;
	MAIL_DAILY_INBOUND_BYTE_LIMIT: 268435456;
	MAIL_DAILY_SUMMARIZATION_LIMIT: 100;
	MAIL_INSTALLATIONS: DurableObjectNamespace<import("./src/index").MailInstallation>;
	ACCOUNTS: Fetcher /* gsv-accounts */;
	GATEWAY: Service /* entrypoint GatewayEntrypoint from gsv-managed-gateway */;
	INFERENCE: Service /* entrypoint InferenceService from gsv-inference */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MailInstallation";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAIL_DOMAIN" | "GSV_BASE_DOMAIN" | "MAIL_MAX_MESSAGE_BYTES" | "MAIL_DAILY_INBOUND_MESSAGE_LIMIT" | "MAIL_DAILY_INBOUND_BYTE_LIMIT" | "MAIL_DAILY_SUMMARIZATION_LIMIT">> {}
}
