export const BUILTIN_DEVICES_WORKER_SOURCE = [
  "import { WorkerEntrypoint } from \"cloudflare:workers\";",
  "",
  "function escapeHtml(value) {",
  "  return String(value)",
  "    .replaceAll(\"&\", \"&amp;\")",
  "    .replaceAll(\"<\", \"&lt;\")",
  "    .replaceAll(\">\", \"&gt;\")",
  "    .replaceAll('\"', \"&quot;\")",
  "    .replaceAll(\"'\", \"&#39;\");",
  "}",
  "",
  "function formatTimestamp(value) {",
  "  if (typeof value !== \"number\" || !Number.isFinite(value)) {",
  "    return \"-\";",
  "  }",
  "  const date = new Date(value);",
  "  return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString();",
  "}",
  "",
  "function renderDeviceList(devices, selectedDeviceId, routeBase, includeOffline) {",
  "  if (!Array.isArray(devices) || devices.length === 0) {",
  "    return '<article class=\"panel\"><p class=\"muted\">No devices found.</p></article>';",
  "  }",
  "",
  "  return devices.map((device) => {",
  "    const selected = device.deviceId === selectedDeviceId;",
  "    const href = `${routeBase}?deviceId=${encodeURIComponent(device.deviceId)}${includeOffline ? \"&includeOffline=1\" : \"\"}`;",
  "    return `",
  "      <a class=\"device-row${selected ? \" is-selected\" : \"\"}\" href=\"${href}\">",
  "        <div class=\"device-row-main\">",
  "          <h3>${escapeHtml(device.deviceId ?? \"device\")}</h3>",
  "          <p>${escapeHtml(device.platform ?? \"unknown\")} · ${escapeHtml(device.version ?? \"-\")}</p>",
  "        </div>",
  "        <span class=\"device-status ${device.online ? \"is-online\" : \"is-offline\"}\">${device.online ? \"online\" : \"offline\"}</span>",
  "      </a>`;",
  "  }).join(\"\");",
  "}",
  "",
  "function renderDeviceDetail(detail) {",
  "  if (!detail) {",
  "    return '<article class=\"panel\"><p class=\"eyebrow\">Details</p><h2>No device selected</h2><p class=\"muted\">Choose a device from the list to inspect it.</p></article>';",
  "  }",
  "",
  "  const implementsList = Array.isArray(detail.implements) && detail.implements.length > 0",
  "    ? detail.implements.map((item) => `<span class=\"tag\">${escapeHtml(item)}</span>`).join(\"\")",
  "    : '<span class=\"tag\">none</span>';",
  "",
  "  return `",
  "    <article class=\"panel detail-card\">",
  "      <p class=\"eyebrow\">Details</p>",
  "      <h2>${escapeHtml(detail.deviceId ?? \"device\")}</h2>",
  "      <div class=\"detail-grid\">",
  "        <div><span class=\"detail-label\">Owner UID</span><strong>${escapeHtml(detail.ownerUid ?? \"-\")}</strong></div>",
  "        <div><span class=\"detail-label\">Platform</span><strong>${escapeHtml(detail.platform ?? \"-\")}</strong></div>",
  "        <div><span class=\"detail-label\">Version</span><strong>${escapeHtml(detail.version ?? \"-\")}</strong></div>",
  "        <div><span class=\"detail-label\">Status</span><strong>${detail.online ? \"online\" : \"offline\"}</strong></div>",
  "        <div><span class=\"detail-label\">First seen</span><strong>${escapeHtml(formatTimestamp(detail.firstSeenAt))}</strong></div>",
  "        <div><span class=\"detail-label\">Last seen</span><strong>${escapeHtml(formatTimestamp(detail.lastSeenAt))}</strong></div>",
  "      </div>",
  "      <div style=\"margin-top: 16px;\">",
  "        <span class=\"detail-label\">Implements</span>",
  "        <div class=\"tag-row\">${implementsList}</div>",
  "      </div>",
  "    </article>`;",
  "}",
  "",
  "function renderPage(frame, devices, detail, includeOffline, errorText) {",
  "  const routeBase = frame.routeBase ?? \"/apps/devices\";",
  "  const selectedDeviceId = detail?.deviceId ?? null;",
  "  return `<!doctype html>",
  "<html lang=\"en\">",
  "  <head>",
  "    <meta charset=\"utf-8\" />",
  "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
  "    <title>Devices</title>",
  "    <link rel=\"stylesheet\" href=\"/runtime/theme.css\" />",
  "    <style>",
  "      body { margin: 0; font-family: \"Space Grotesk\", \"Avenir Next\", sans-serif; color: var(--text); background: linear-gradient(180deg, rgba(10, 16, 34, 0.96), rgba(7, 12, 28, 0.98)); }",
  "      main { max-width: 1180px; margin: 0 auto; padding: 24px; display: grid; gap: 18px; }",
  "      .hero, .panel { border: 1px solid var(--edge); background: var(--panel); backdrop-filter: blur(16px); border-radius: 22px; box-shadow: 0 22px 60px rgba(0, 0, 0, 0.35); }",
  "      .hero { padding: 24px; }",
  "      .eyebrow { text-transform: uppercase; letter-spacing: 0.16em; font-size: 11px; color: var(--accent); margin: 0 0 8px; }",
  "      h1, h2, h3, p { margin: 0; }",
  "      h1 { font-size: clamp(28px, 5vw, 52px); margin-bottom: 8px; }",
  "      h2 { font-size: 24px; margin-bottom: 10px; }",
  "      h3 { font-size: 16px; margin-bottom: 4px; }",
  "      p { line-height: 1.55; }",
  "      .muted { color: var(--muted); }",
  "      .toolbar { display: flex; flex-wrap: wrap; align-items: center; gap: 12px; margin-top: 18px; }",
  "      .toolbar a, .toolbar button { border: 1px solid rgba(138, 224, 255, 0.22); background: rgba(138, 224, 255, 0.12); color: var(--text); border-radius: 999px; padding: 8px 12px; font: inherit; text-decoration: none; }",
  "      .layout { display: grid; grid-template-columns: minmax(300px, 420px) minmax(0, 1fr); gap: 18px; }",
  "      .list-panel { padding: 14px; display: grid; gap: 10px; }",
  "      .device-row { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 12px; align-items: center; padding: 14px 16px; border-radius: 16px; border: 1px solid rgba(138, 224, 255, 0.12); background: rgba(138, 224, 255, 0.06); color: inherit; text-decoration: none; }",
  "      .device-row.is-selected { border-color: rgba(138, 224, 255, 0.32); background: rgba(138, 224, 255, 0.12); }",
  "      .device-status { display: inline-flex; align-items: center; justify-content: center; border-radius: 999px; padding: 4px 10px; font-size: 12px; }",
  "      .device-status.is-online { background: rgba(92, 210, 168, 0.16); color: #8ef0c9; }",
  "      .device-status.is-offline { background: rgba(255, 111, 111, 0.12); color: #ffadad; }",
  "      .detail-card { padding: 22px; }",
  "      .detail-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 14px; }",
  "      .detail-label { display: block; font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--muted); margin-bottom: 6px; }",
  "      .tag-row { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 8px; }",
  "      .tag { display: inline-flex; align-items: center; gap: 6px; padding: 6px 10px; border-radius: 999px; background: rgba(138, 224, 255, 0.12); border: 1px solid rgba(138, 224, 255, 0.16); color: var(--text); font-size: 12px; }",
  "      .error { padding: 14px 16px; border-radius: 16px; border: 1px solid rgba(255, 111, 111, 0.22); background: rgba(255, 111, 111, 0.12); color: #ffd3d3; }",
  "      @media (max-width: 900px) { main { padding: 16px; } .layout { grid-template-columns: 1fr; } .hero, .panel { border-radius: 18px; } }",
  "    </style>",
  "  </head>",
  "  <body>",
  "    <main>",
  "      <section class=\"hero\">",
  "        <p class=\"eyebrow\">Package-served app</p>",
  "        <h1>Devices</h1>",
  "        <p>Live device inventory rendered directly by the package worker using the request-scoped <code>KERNEL.request(...)</code> binding.</p>",
  "        <div class=\"toolbar\">",
  "          <a href=\"${routeBase}${includeOffline ? \"?includeOffline=1\" : \"\"}\">Refresh</a>",
  "          ${includeOffline ? `<a href=\"${routeBase}\">Hide offline</a>` : `<a href=\"${routeBase}?includeOffline=1\">Show offline</a>`}",
  "          <span class=\"muted\">viewer ${escapeHtml(frame.username ?? \"user\")}</span>",
  "        </div>",
  "      </section>",
  "      ${errorText ? `<section class=\"error\">${escapeHtml(errorText)}</section>` : \"\"}",
  "      <section class=\"layout\">",
  "        <section class=\"panel list-panel\">${renderDeviceList(devices, selectedDeviceId, routeBase, includeOffline)}</section>",
  "        ${renderDeviceDetail(detail)}",
  "      </section>",
  "    </main>",
  "  </body>",
  "</html>`;",
  "}",
  "",
  "export default class DevicesApp extends WorkerEntrypoint {",
  "  async fetch(request) {",
  "    const appFrame = this.ctx.props.appFrame;",
  "    const kernel = this.ctx.props.kernel;",
  "    if (!appFrame || !kernel) {",
  "      return new Response(\"App frame missing\", { status: 500 });",
  "    }",
  "    const url = new URL(request.url);",
  "    const routeBase = appFrame.routeBase ?? this.env.PACKAGE_ROUTE_BASE ?? \"/apps/devices\";",
  "    if (url.pathname !== routeBase && url.pathname !== `${routeBase}/`) {",
  "      return new Response(\"Not Found\", { status: 404 });",
  "    }",
  "",
  "    const selectedDeviceId = String(url.searchParams.get(\"deviceId\") ?? \"\").trim();",
  "    const includeOffline = url.searchParams.get(\"includeOffline\") === \"1\";",
  "    let devices = [];",
  "    let detail = null;",
  "    let errorText = \"\";",
  "",
  "    try {",
  "      const listing = await kernel.request(\"sys.device.list\", { includeOffline });",
  "      devices = Array.isArray(listing?.devices) ? listing.devices : [];",
  "      if (selectedDeviceId) {",
  "        const detailResult = await kernel.request(\"sys.device.get\", { deviceId: selectedDeviceId });",
  "        detail = detailResult?.device ?? null;",
  "      }",
  "    } catch (error) {",
  "      errorText = error instanceof Error ? error.message : String(error);",
  "    }",
  "",
  "    return new Response(renderPage(appFrame, devices, detail, includeOffline, errorText), {",
  "      headers: {",
  "        \"content-type\": \"text/html; charset=utf-8\",",
  "        \"cache-control\": \"no-store\",",
  "      },",
  "    });",
  "  }",
  "}",
].join("\n");
