export type {
  AdapterAccountStatus,
  AdapterActivity,
  AdapterActor,
  AdapterConnectChallenge,
  AdapterConnectResult,
  AdapterDisconnectResult,
  AdapterInboundMessage,
  AdapterInboundResult,
  AdapterInstallationContext,
  AdapterMedia,
  AdapterOutboundMessage,
  AdapterSendResult,
  AdapterSurface,
  AdapterSurfaceKind,
  AdapterWorkerInterface,
  BinaryBody,
  GatewayFrame,
  GatewayRequestFrame,
  GatewayResponseFrame,
} from "../../shared/src/types";
