export function renderManualPage(topic?: string): string | null {
  const normalized = (topic ?? "").trim().toLowerCase();

  switch (normalized) {
    case "":
    case "help":
      return [
        "GSV manual pages",
        "",
        "Available pages:",
        "  gsv   Platform model, targets, paths, and knowledge systems",
        "  codemode  Run GSV tool scripts from the shell",
        "  notify  User notifications and background job alerts",
        "  wiki  Durable knowledge databases, including the personal wiki",
        "",
        "Usage:",
        "  man gsv",
        "  man codemode",
        "  man notify",
        "  man wiki",
        "",
      ].join("\n");

    case "codemode":
      return [
        "CODEMODE(1)",
        "",
        "NAME",
        "  codemode - run JavaScript blocks with GSV shell and filesystem wrappers",
        "",
        "SYNOPSIS",
        "  codemode <script.js> [options] [-- argv...]",
        "  codemode run <script.js> [options] [-- argv...]",
        "  codemode -e <code> [options] [-- argv...]",
        "",
        "OVERVIEW",
        "  `codemode` runs one async JavaScript block through the same CodeMode runtime exposed",
        "  to agents. Scripts can call `await shell(input, options)` and `fs.read`, `fs.write`,",
        "  `fs.edit`, `fs.delete`, or `fs.search`.",
        "",
        "OPTIONS",
        "  --target <device>   Default target for shell and filesystem calls.",
        "  --cwd <path>        Default cwd for shell calls and relative filesystem paths.",
        "  --json              Print the full result envelope.",
        "  --arg key=value     Expose scalar args[key] to the script.",
        "  --args-json <json>  Expose structured args to the script.",
        "",
        "SCRIPT CONTEXT",
        "  argv                Positional arguments after `--`.",
        "  args                Values supplied with --arg or --args-json.",
        "",
      ].join("\n");

    case "gsv":
      return [
        "GSV(1)",
        "",
        "NAME",
        "  gsv - distributed AI operating environment",
        "",
        "OVERVIEW",
        "  GSV gives AI processes a Linux-like filesystem, explicit tools, and multiple execution targets.",
        "  `gsv` is the local control target. Other targets are user devices or nodes that may expose",
        "  shell and filesystem operations when they are online and authorized.",
        "",
        "STANDING CONTEXT",
        "  ~/context.d/*.md",
        "      Small curated notes that are always loaded into prompt context.",
        "",
        "DURABLE KNOWLEDGE",
        "  ~/knowledge/",
        "      Durable markdown knowledge pages. This is not loaded into the prompt automatically.",
        "      Use `wiki` for both broader knowledge bases and the conventional `personal` database.",
        "",
        "KNOWN PATHS",
        "  /home/<user>   User home, including standing context and durable knowledge",
        "  /workspaces    Task workspaces and user artifacts",
        "  /var           Runtime-managed state, caches, and generated system data",
        "  /etc           System manuals and stable operator documentation",
        "  /sys           Live kernel configuration and runtime control surfaces",
        "  /proc          Live process and runtime inspection surfaces",
        "  /dev           Device-like virtual endpoints",
        "",
        "KNOWLEDGE WORKFLOWS",
        "  Use direct page writes when the target note is clear and the information is durable.",
        "  Use inbox staging when the information is tentative, uncertain, or needs review.",
        "  Use `search` to find candidate notes and `query` when you want a compact brief with references.",
        "",
      ].join("\n");

    case "wiki":
      return [
        "WIKI(1)",
        "",
        "NAME",
        "  wiki - manage durable knowledge databases",
        "",
        "OVERVIEW",
        "  `wiki` manages named knowledge databases made of markdown pages and live source references.",
        "  Use it for broader domain knowledge, research notes, product docs, and the conventional `personal` database.",
        "",
        "SEARCH VS QUERY",
        "  wiki search <query> [--prefix PREFIX]",
        "      Find matching notes with snippets.",
        "  wiki query <query> [--prefix PREFIX ...]",
        "      Return a compact brief and references from the best matching notes.",
        "",
        "DATABASE SETUP",
        "  wiki db init product-alpha --title \"Product Alpha\"",
        "  wiki db init personal --title \"Personal\"",
        "",
        "DIRECT PAGE WRITES",
        "  wiki write product-alpha/pages/auth.md --text \"# Auth\\n\\n## Summary\\nCurrent auth model.\"",
        "  wiki write personal/pages/people/alice.md --text \"# Alice\\n\\n## Preferences\\n- Prefers concise replies\"",
        "",
        "LIVE SOURCES",
        "  Source references use the form:",
        "    target:/absolute/path::Optional title",
        "  Quote the whole value when the title contains spaces.",
        "  Example:",
        "    wiki source add product-alpha/pages/auth.md --source \"gsv:/workspaces/gsv/specs/auth.md::Auth spec\"",
        "",
        "INGEST AND COMPILE",
        "  Use ingest when you want to stage or create a page from one or more live sources.",
        "  Example:",
        "    wiki ingest product-alpha --source \"gsv:/workspaces/gsv/docs/alpha-plan.md::Alpha plan\" --title \"Adapter UX inputs\"",
        "    wiki list product-alpha/inbox -r",
        "    wiki compile product-alpha product-alpha/inbox/<candidate>.md product-alpha/pages/adapter-ux.md",
        "",
        "PERSONAL KNOWLEDGE",
        "  Use the `personal` database for durable notes about the user, people, projects, and other standing context.",
        "  Examples:",
        "    wiki query \"What should I remember about Alice?\" --prefix personal/pages",
        "    wiki ingest personal --source \"gsv:/workspaces/chat/alice.md::Alice onboarding notes\"",
        "    wiki compile personal personal/inbox/<candidate>.md personal/pages/people/alice.md",
        "",
      ].join("\n");

    case "notify":
      return [
        "NOTIFY(1)",
        "",
        "NAME",
        "  notify - send and manage user notifications",
        "",
        "OVERVIEW",
        "  `notify` creates durable user notifications and manages their read/dismissed state.",
        "  Notifications appear in the web shell toast/panel and can be delivered by other surfaces later.",
        "",
        "SEND",
        "  notify send --title \"Wiki build finished\" --body \"product-alpha is ready\" --level success",
        "",
        "LIST",
        "  notify list",
        "  notify list --unread",
        "  notify list --dismissed",
        "",
        "STATE CHANGES",
        "  notify read <notification-id>",
        "  notify dismiss <notification-id>",
        "",
        "LEVELS",
        "  info, success, warning, error",
        "",
      ].join("\n");

    default:
      return null;
  }
}
