import { nativeCommandSynopsis } from "./shell/discovery";

export function renderManualPage(topic: string): string | null {
  const normalized = topic.trim().toLowerCase();

  switch (normalized) {
    case "llm":
      return [
        "LLM(1)",
        "",
        "NAME",
        "  llm - generate one text response with the configured AI model",
        "",
        "SYNOPSIS",
        "  llm [OPTIONS] PROMPT...",
        "  printf 'PROMPT' | llm [OPTIONS]",
        "",
        "OVERVIEW",
        "  `llm` wraps ai.text.generate for one-shot text generation. It uses the",
        "  same configured provider/model as processes unless overridden with a preset",
        "  or explicit provider/model flags. It does not run tools or an agent loop.",
        "",
        "OPTIONS",
        "  --system TEXT       System prompt for this request.",
        "  --preset NAME_OR_ID Resolve model settings from a saved model preset.",
        "  --provider PROVIDER Override config/ai/provider for this request.",
        "  --model MODEL       Override config/ai/model for this request.",
        "  --max-tokens N      Maximum output tokens.",
        "  --reasoning LEVEL   inherit, off, minimal, low, medium, high, or xhigh.",
        "  --timeout-ms N      Request timeout in milliseconds.",
        "  --json              Print the full ai.text.generate result.",
        "",
        "EXAMPLES",
        "  llm 'Summarize this in one sentence.'",
        "  printf 'Release notes...' | llm --system 'Return three bullets.'",
        "  llm --preset fast --max-tokens 128 'Suggest a concise task label.'",
        "  llm --provider anthropic --model claude-sonnet-4-6 --json 'ping'",
        "",
      ].join("\n");

    case "crontab":
      return [
        "CRONTAB(1)",
        "",
        "NAME",
        "  crontab - install, list, and remove cron tables",
        "",
        "SYNOPSIS",
        "  crontab -l [-u user]",
        "  crontab -r [-u user]",
        "  crontab FILE [-u user]",
        "  crontab -e [-u user]",
        "",
        "FILES",
        "  /var/spool/cron/<user>  Per-user crontab.",
        "  /etc/cron.d/<name>      System crontab with an extra user field.",
        "",
        "FORMAT",
        "  minute hour day-of-month month day-of-week command",
        "  CRON_TZ=Europe/Amsterdam",
        "",
        "OVERVIEW",
        "  crontab is the normal interface for recurring background shell commands.",
        "  The crontab file is desired state. Reinstalling it deletes and recreates",
        "  the linked Kernel schedule rows, so sched ids for cron lines are not stable.",
        "  Use sched list for operational status such as next fire, last status, error,",
        "  source file, and target.",
        "  Cron commands have no process-backed caller. Do not put proc delegate in a",
        "  crontab; use sched add --here when an event should run the current process",
        "  and preserve its current authorized reply surface when one exists.",
        "  A successful proc spawn cron run means the child was accepted, not that it",
        "  completed or delivered its answer. Detached answers remain in child history.",
        "",
        "EXAMPLES",
        "  crontab -l",
        "  crontab jobs.cron",
        "  printf '0 9 * * * proc spawn --non-interactive --label refresh-index \"Refresh the search index.\"\\n' > /var/spool/cron/sam",
        "",
      ].join("\n");

    case "targets":
    case "devices":
      return [
        "TARGETS(1)",
        "",
        "NAME",
        "  targets - discover Unix-shaped capability environments",
        "",
        "SYNOPSIS",
        "  targets list [--all|--online] [--search QUERY] [--limit N] [--offset N] [--json]",
        "  targets search <query> [--all|--online] [--limit N] [--offset N] [--json]",
        "  targets show <target-id> [--json]",
        "  devices ...",
        "",
        "OVERVIEW",
        "  `targets` lists registered target ids and their current online state. Offline",
        "  targets remain visible but cannot accept Shell, filesystem, CodeMode, or cp",
        "  operations until they reconnect. Use --online to list only reachable targets.",
        "  The prompt only includes a compact online sample, so use this command when",
        "  more registered targets may exist.",
        "",
        "PROVIDERS",
        "  kernel   Native GSV capability environment.",
        "  device   Registered targets backed by machines or browser profiles.",
        "",
        "EXAMPLES",
        "  targets list",
        "  targets list --online",
        "  targets search browser-extension",
        "  targets show rearden:brave",
        "",
      ].join("\n");

    case "mcp":
      return [
        "MCP(1)",
        "",
        "NAME",
        "  mcp - manage connected MCP servers and call MCP tools",
        "",
        "SYNOPSIS",
        "  mcp status [--json]",
        "  mcp list [--json]",
        "  mcp tools [server-id|name] [--json]",
        "  mcp describe <server-id|name> [tool-name|codemode-function] [--json]",
        "  mcp search <query> [--json]",
        "  mcp codemode [server-id|name] [--json]",
        "  mcp add <name> <url> [--transport auto|streamable-http|sse] [--callback-host origin] [--header key=value] [--json]",
        "  mcp refresh <server-id> [--json]",
        "  mcp call <server-id|name> <tool-name|codemode-function> [--arg key=value] [--args-json json] [--json]",
        "  mcp remove <server-id> [--json]",
        "",
        "OVERVIEW",
        "  `mcp` wraps sys.mcp.*. It keeps MCP behind the runtime boundary instead of",
        "  exposing every remote MCP tool as a direct model tool.",
        "  Use `mcp status` for server health, `mcp tools` or `mcp search` to discover",
        "  available tools, and `mcp codemode` to print a CodeMode discovery snippet.",
        "  Tool listings include the generated CodeMode function names used by agents.",
        "  OAuth-capable servers return auth_url from add/list; open that URL and finish",
        "  sign-in through /oauth/callback before refreshing or calling tools.",
        "",
        "EXAMPLES",
        "  mcp status",
        "  mcp add github https://mcp.github.com/mcp --transport streamable-http",
        "  mcp tools github",
        "  mcp describe github search_issues",
        "  mcp call github search_issues --args-json '{\"query\":\"gsv\"}' --json",
        "",
      ].join("\n");

    case "message":
      return [
        "MESSAGE(1)",
        "",
        "NAME",
        "  message - reply, send, and route external conversations",
        "",
        "SYNOPSIS",
        ...manualSynopsis("message"),
        "",
        "OVERVIEW",
        "  `message send` commits a user-visible message without finishing the run.",
        "  Ordinary assistant text remains Process activity. Run `yield` when work is",
        "  complete, or append `&& yield` to a final literal message block.",
        "",
        "CURRENT",
        "  `message current` reports the current run's directed endpoint.",
        "  It describes the transport without exposing provider account or surface ids.",
        "",
        "DESTINATIONS",
        "  `message destinations` lists authorized online adapter destinations observed",
        "  for the calling user. `--all` also includes known destinations whose adapter",
        "  account is offline. Group, channel, and thread destinations appear only after",
        "  the linked actor addresses GSV on that exact surface. Destination ids are",
        "  opaque GSV references; copy one from this list instead of using provider ids.",
        "",
        "ROUTES",
        "  `message route show` and `message route list` inspect adapter routing. Set and",
        "  clear manage persistent mappings for groups, channels, and threads. On the",
        "  exact private DM that started its current run, only the personal intelligence",
        "  can set an owned non-personal process as a temporary work direct line.",
        "  Use /ship inside that DM to return to Ship. --to defaults to",
        "  `here`, the adapter surface that started the current run. An explicit",
        "  destination is an opaque id or unambiguous label from",
        "  `message destinations --all`.",
        "  --process accepts a full or unique process-id prefix or an unambiguous label.",
        "  Route changes affect future inbound messages. The current run's direct messages stay",
        "  directed to its original surface. Spawn a process before routing a shared surface.",
        "",
        "SEND",
        "  A literal `message send <<'GSV_MESSAGE'` block sends on the active run's",
        "  directed endpoint without interpreting the message contents. The run continues.",
        "  --to here selects the current adapter reply surface. An explicit send to that",
        "  or another destination requires --also during an active run, acknowledging that",
        "  the extra message is intentional. A separate send does not finish the run.",
        "  --attach streams one GSV filesystem file. --mime overrides inferred content",
        "  type. Copy a connected-machine file to GSV before attaching it.",
        "",
        "ATTACH",
        "  `message attach` adds one or more GSV filesystem files to this run's next",
        "  current-conversation message. Files are",
        "  staged as process-owned media; an existing path under this process's",
        "  /var/media directory is reused. --mime overrides the inferred type for",
        "  a single file.",
        "",
        "CONTACT HISTORY AND DELIVERY",
        "  `message history --with CONTACT_ID` reads that Contact conversation with",
        "  stable authors, resources, and pagination. A conversation id is also accepted.",
        "  A Contact send reports accepted once GSV durably owns it; this is distinct",
        "  from remote confirmation. Retain delivery_id and use `message delivery show`",
        "  to observe queued, delivered, or failed state.",
        "",
        "EXAMPLES",
        "  message current",
        "  message destinations --all",
        "  message route show",
        "  message route set --process proc:PROCESS_ID",
        "  message route clear --to DESTINATION",
        "  message send <<'GSV_MESSAGE' && yield",
        "  The report is ready.",
        "  GSV_MESSAGE",
        "  yield",
        "  message send --to whatsapp --message 'The report is ready there too.' --also",
        "  cp laptop:/home/alice/report.pdf /tmp/report.pdf",
        "  message attach /tmp/report.pdf",
        "  message send --to here --message 'Here it is.' --attach /tmp/report.pdf --also",
        "  message send --to DESTINATION --message 'Retry' --delivery-id DELIVERY_ID --also",
        "  message history --with contact:CONTACT_ID --limit 50",
        "  message delivery show delivery:DELIVERY_ID",
        "",
      ].join("\n");

    case "yield":
      return [
        "YIELD(1)",
        "",
        "NAME",
        "  yield - finish the active run without ending its Process",
        "",
        "SYNOPSIS",
        "  yield",
        "",
        "DESCRIPTION",
        "  Finish the current human-facing run and return control to GSV. The durable",
        "  Process remains available for future user messages and system events.",
        "  A bare yield completes without another user-visible message. Compose a final",
        "  delivery as `message send ... && yield`; if sending fails, yield does not run.",
        "  Invoke yield directly through Shell, not through CodeMode.",
        "",
      ].join("\n");

    case "mail":
      return [
        "MAIL(1)",
        "",
        "NAME",
        "  mail - read and send managed email",
        "",
        "SYNOPSIS",
        ...manualSynopsis("mail"),
        "",
        "OVERVIEW",
        "  `mail send` queues one plain-text email to one recipient. `mail reply`",
        "  derives the recipient and threading headers from an owner-scoped inbox",
        "  message. `mail status` reads the eventual state for a delivery id.",
        "  Sending requires managed mail and the mail.send capability. The command",
        "  runs beneath shell.exec, so that outer shell approval authorizes the send.",
        "",
        "DELIVERY",
        "  A successful command normally reports queued after GSV durably owns Queue",
        "  publication. It does not mean the recipient received the message. Retain",
        "  delivery_id and use `mail status` to observe accepted, failed, or unknown.",
        "  Pass --delivery-id when retrying outside the same durable shell request.",
        "",
        "LIMITS",
        "  Version one supports a non-empty plain-text body up to 1 MiB and exactly",
        "  one recipient. It does not support HTML, CC, BCC, or attachments.",
        "",
        "EXAMPLES",
        "  mail send --to person@example.com --subject 'Hello' --message 'Hello from GSV'",
        "  mail reply MESSAGE_ID --body ./reply.txt",
        "  mail status DELIVERY_ID",
        "",
      ].join("\n");

    case "sched":
      return [
        "SCHED(1)",
        "",
        "NAME",
        "  sched - schedule chat prompts and control Kernel schedules",
        "",
        "SYNOPSIS",
        ...manualSynopsis("sched"),
        "",
        "OVERVIEW",
        "  `sched` wraps sched.* for chat-visible prompts, direct adapter delivery,",
        "  inspection, force-runs, and compatibility.",
        "  Use crontab(1) or /var/spool/cron/<user> for background shell commands.",
        "  sched list shows operational records. For crontab-backed rows, SOURCE",
        "  points back to the cron file and line that generated the record.",
        "  --all includes disabled schedules, not other users' schedules.",
        "  Crontab-backed schedule ids are regenerated when the crontab is reinstalled.",
        "",
        "HERE ADD",
        "  --here requires a process-backed shell. Choose exactly one of --every,",
        "  --cron, --after, or --at.",
        "  It creates a process.event target for the current process. When invoked during",
        "  an adapter run, it captures that authorized destination so the future final",
        "  answer returns there. Otherwise the answer stays in the process history.",
        "  The target remains bound to the process id; recreate it after proc kill.",
        "  --timezone applies to --cron and defaults to the configured server timezone.",
        "  --at requires a future ISO timestamp with Z or an explicit numeric UTC offset.",
        "  A successful firing records event admission, not a completed model turn or reply.",
        "",
        "TO ADD",
        "  --to resolves an authorized adapter destination, including known offline",
        "  destinations, and creates a direct scheduled delivery. It sends the supplied",
        "  text without running an agent.",
        "",
        "EXAMPLES",
        "  sched add --here --name animal-facts --every 2m --message 'Send one obscure animal fact.'",
        "  sched add --here --name daily-brief --cron '0 9 * * *' --timezone Europe/Amsterdam --message 'Prepare the daily brief.'",
        "  sched add --to telegram --name standup --cron '0 9 * * 1-5' --message 'Standup starts now.'",
        "",
        "LOW-LEVEL ADD",
        "  sched add --json JSON accepts the raw sched.add syscall payload.",
        "  Prefer --here for agent work, --to for direct adapter text, or crontab FILE",
        "  for background shell commands.",
        "",
      ].join("\n");

    case "proc":
      return [
        "PROC(1)",
        "",
        "NAME",
        "  proc - inspect, create, and manage processes",
        "",
        "SYNOPSIS",
        "  proc self",
        "  proc list",
        "  proc agents [--json]",
        "  proc spawn [--as ACCOUNT] [--non-interactive] [--label LABEL] [--prompt TEXT] [--parent PID] [--cwd PATH] [--] [prompt]",
        "  proc spawn --json JSON",
        "  proc reset [--pid PID]",
        "  proc kill PID [--no-archive]",
        "  proc delegate [--as ACCOUNT] [--label LABEL] [--parent PID] [--cwd PATH] [--timeout 10m] [--responsibility ID] <task>",
        "  proc segments [--pid PID]",
        "  proc policy [--pid PID] [--overflow auto-compact|fail] [--compact-at N] [--keep-last N]",
        "  proc history [--pid PID] [--tail] [--limit N] [--offset N] [--json] [--full]",
        "  proc segment <segment-id> [--pid PID] [--limit N] [--offset N] [--json]",
        "  proc compact [--pid PID] (--keep-last N | --through-message-id ID) [--summary TEXT | --generate-summary]",
        "  proc fork (<segment-id> | --message-id ID) [--pid PID] [--label LABEL] [--segment-only]",
        "  proc send <pid> [--metadata-json json] <message>",
        "  proc call <pid> [--metadata-json json] [--timeout 60s] <message>",
        "",
        "OVERVIEW",
        "  `proc` is the process IPC userland command. It wraps proc.ipc syscalls instead",
        "  of exposing a model-specific ProcessMessage tool.",
        "",
        "COMMANDS",
        "  self",
        "      Print the current GSV process id. This requires a process-backed shell;",
        "      a top-level user shell has no current process. The same value is $GSV_PID.",
        "  list",
        "      Show processes visible to the current user.",
        "  agents",
        "      Show the accounts you can run a process as: your own identity, your",
        "      personal agent and agent accounts",
        "      whose group you belong to.",
        "  spawn",
        "      Create a fresh process. With no --as it inherits the current process's",
        "      run-as identity, or uses your personal agent at the top level. Pass",
        "      --as ACCOUNT (a username or uid) to run as another account.",
        "      A prompt on spawn starts fire-and-forget work. Use --non-interactive for",
        "      cron jobs. Schedule status ok means spawn acceptance, not child completion",
        "      or delivery; an answer remains in the child process history.",
        "  reset",
        "      Archive and clear a process's history, queued work, and media.",
        "  kill",
        "      Archive and remove a process. Pass --no-archive to remove it directly.",
        "  delegate",
        "      Create a non-interactive child process for bounded work. Returns an",
        "      in-progress task handle immediately; completion or timeout is delivered",
        "      back to the caller as a delegated task event. This requires a",
        "      process-backed caller; do not put proc delegate in a crontab. With",
        "      --responsibility, assignment and its deadline are durable before the",
        "      child starts, and failed IPC admission returns the record to Ship.",
        "  segments",
        "      List compacted history archive segments for a process.",
        "  policy",
        "      Show or set the visible context-overflow policy for a process history.",
        "  history",
        "      Read the live transcript for this process or another visible process.",
        "      Output is content-bounded by default; use --full or --json for raw content.",
        "  segment",
        "      Read archived messages from a compacted segment without restoring them.",
        "  compact",
        "      Archive a history prefix and replace it with a visible summary marker.",
        "  fork",
        "      Branch a new process from a live message or a compacted segment.",
        "  send",
        "      Send asynchronous mail to another process owned by the same user.",
        "  call",
        "      Send bounded work to an existing process. The kernel delivers completion",
        "      or timeout back to the calling process as a delegated task event.",
        "",
        "OPTIONS",
        "  --pid <pid>              Process target. Defaults to the current process; it is",
        "                           required from a top-level shell.",
        "  --no-archive             Skip archival before proc kill removes the process.",
        "  --non-interactive        Create a detached process suitable for background work.",
        "  --                       End spawn options before a positional prompt beginning with -.",
        "  --keep-last <n>          Compact all but the newest n messages.",
        "  --through-message-id <id> Compact through a specific message id.",
        "  --summary <text>         Markdown summary inserted into the live history.",
        "  --generate-summary       Ask the process model to write the compact summary.",
        "  --overflow <mode>        Policy mode: auto-compact or fail.",
        "  --compact-at <n>         Policy pressure threshold from 0 to 1.",
        "  --label <label>          Label for the process created by proc fork.",
        "  --message-id <id>        Live message id to branch from with proc fork.",
        "  --tail                   Read the latest live history page.",
        "  --before-message-id <id> Read live history before this message id.",
        "  --after-message-id <id>  Read live history after this message id.",
        "  --segment-only           Fork only the archived segment, without the kept suffix.",
        "  --limit <n>              Maximum live or archived messages to print.",
        "  --offset <n>             Live or archived message offset.",
        "  --json                   Print raw JSON for proc history or proc segment.",
        "  --full                   Do not truncate live proc history message content.",
        "  --max-content-chars <n>  Per-message live history content budget.",
        "  --metadata-json <json>   Optional JSON object delivered with the message.",
        "  --timeout <duration>     Call deadline. Supports ms, s, and m suffixes.",
        "  --responsibility <id>    Assign an existing responsibility during delegation.",
        "",
      ].join("\n");

    case "codemode":
      return [
        "CODEMODE(1)",
        "",
        "NAME",
        "  codemode - run JavaScript blocks with GSV shell and filesystem wrappers",
        "",
        "SYNOPSIS",
        "  codemode <script.js> [options] [-- argv...]",
        "  codemode run <script.js> [options] [-- argv...]",
        "  codemode -e <code> [options] [-- argv...]",
        "",
        "OVERVIEW",
        "  `codemode` runs one async JavaScript block through the same CodeMode runtime exposed",
        "  to agents. Scripts can call `await shell(input, options)`, `fs.read`, `fs.write`,",
        "  `fs.edit`, `fs.delete`, `fs.search`, `mail.send`, and connected MCP tools as generated async",
        "  functions. Inspect `mcpTools` for their names and schemas. MCP functions return",
        "  structured output directly when available.",
        "  Script files and -e code are treated as async function bodies. Use top-level await",
        "  freely, and use an explicit return statement for the value to print.",
        "",
        "OPTIONS",
        "  --target <target>   Default target for shell and filesystem calls.",
        "  --cwd <path>        Default cwd for shell calls and relative filesystem paths.",
        "  --json              Print the full result envelope.",
        "  --arg key=value     Expose scalar args[key] to the script.",
        "  --args-json <json>  Expose structured args to the script.",
        "",
        "SCRIPT CONTEXT",
        "  argv                Positional arguments after `--`.",
        "  args                Values supplied with --arg or --args-json.",
        "  shell(input, opts)  Run or continue a shell command.",
        "  fs                  Filesystem helpers: read, write, edit, delete, search.",
        "  mail.send(args)     Queue a new message or a reply through managed mail.",
        "  mcpTools            Metadata and schemas for generated MCP tool functions.",
        "",
        "RESULTS",
        "  Without --json, completed runs print only the returned value.",
        "  With --json, runs print { status, result?, error?, logs? }.",
        "  Failed runs exit 1.",
        "",
        "EXAMPLES",
        "  codemode -e 'return await shell(\"pwd\")'",
        "  codemode ./check.js --cwd ~/projects/gsv -- arg1 arg2",
        "",
      ].join("\n");

    case "gsv":
      return [
        "GSV(1)",
        "",
        "NAME",
        "  gsv - distributed AI operating environment",
        "",
        "OVERVIEW",
        "  GSV gives AI processes explicit tools and Unix-shaped capability environments called targets.",
        "  `gsv` is the native environment. Other targets may be backed by machines, browser profiles,",
        "  or services and expose only the operations they coherently implement and the caller may use.",
        "",
        "STANDING CONTEXT",
        "  ~/context.d/*.md",
        "      Small curated notes that are always loaded into prompt context.",
        "  ~/skills.d/*",
        "      Reusable process skills. Prompt context lists compact skill ids;",
        "      use `skills show <skill>` to read full SKILL.md content.",
        "",
        "DURABLE KNOWLEDGE",
        "  wiki",
        "      Durable markdown knowledge lives in repo-backed wiki collections.",
        "      This is not loaded into the prompt automatically; use `wiki` or search",
        "      `/src/repos/<owner>/<wiki>` to retrieve it.",
        "",
        "KNOWN PATHS",
        "  /home/<user>   User home, including standing context and ordinary files",
        "  /var           Runtime-managed state, caches, and generated system data",
        "  /etc           System manuals and stable operator documentation",
        "  /src/repos     Visible ripgit repositories, including wiki repos",
        "  /sys           Live kernel configuration and runtime control surfaces",
        "  /proc          Live process and runtime inspection surfaces",
        "  /dev           Device-like virtual endpoints",
        "",
        "KNOWLEDGE WORKFLOWS",
        "  Use `wiki db init <id>` to create a wiki repo, then edit pages directly",
        "  under `/src/repos/<owner>/<id>` when the target note is clear.",
        "  Use source references when a page should cite live files without copying a source corpus.",
        "  Use `wiki search` to find matching notes and `wiki brief` when you want compact snippets.",
        "",
      ].join("\n");

    case "rgit":
    case "ripgit":
      return [
        "RGIT(1)",
        "",
        "NAME",
        "  rgit - inspect ripgit repositories",
        "",
        "OVERVIEW",
        "  `rgit` is the native shell command for ripgit-backed repositories.",
        "  Repos live under `/src/repos/<owner>/<repo>`. Writes under writable",
        "  repo paths commit immediately to the configured ripgit ref.",
        "",
        "INSPECTION",
        "  rgit list [--owner USER]",
        "  rgit info <repo|--here>",
        "  rgit path <repo|--here>",
        "  rgit read <repo|--here> [path] [--ref REF]",
        "  rgit search <repo|--here> <query> [--prefix PATH] [--ref REF]",
        "  rgit refs <repo|--here>",
        "  rgit log <repo|--here> [--ref REF] [--limit N] [--offset N]",
        "  rgit diff <repo|--here> <commit> [--context N]",
        "  rgit compare <repo|--here> <base> <head> [--stat] [--context N]",
        "",
        "MUTATION",
        "  rgit create owner/repo [--ref main] [--description TEXT]",
        "  rgit import <repo|--here> --from URL [--ref REF] [--remote-ref REF]",
        "  rgit pull <repo|--here> [--ref REF] [--remote-ref REF]",
        "",
        "NOTES",
        "  `--here` is the only cwd-based shortcut. It requires cwd under",
        "  `/src/repos/<owner>/<repo>` and resolves that repo before acting.",
        "",
      ].join("\n");

    case "skills":
      return [
        "SKILLS(1)",
        "",
        "NAME",
        "  skills - discover, persist, and validate reusable process skills",
        "",
        "OVERVIEW",
        "  `skills` reads layered skills.d directories and shows reusable workflows",
        "  without dumping their full contents into every prompt. Prompt context keeps",
        "  only a compact skill index; use this command to inspect the full skill.",
        "",
        "SOURCES",
        "  owner and agent home skills.d",
        "      Skills from the owning user's home and, for a distinct run-as agent,",
        "      that agent's home. Both are backed by their account home repositories.",
        "COMMANDS",
        ...manualSynopsis("skills"),
        "",
        "DETAILS",
        "  skills list",
        "      List top-level skill ids, source labels, writable state, and descriptions.",
        "  skills list <skill>",
        "      List immediate nested child skills under a parent skill.",
        "  skills tree [skill]",
        "      Print the skill hierarchy, or a subtree rooted at a parent skill.",
        "      `skills topics` is an alias.",
        "  skills search <query>",
        "      Search ids, descriptions, and skill bodies.",
        "  skills show <skill>",
        "      Print a full SKILL.md and its backing source path.",
        "  skills files <skill>",
        "      List supporting files under the skill directory.",
        "  skills read <skill> <file>",
        "      Read a supporting file such as references/api.md or templates/app.ts.",
        "  skills create <name> --description <text> [--from <body-file>] [--replace]",
        "      Persist a Markdown instruction body as ~/skills.d/<name>/SKILL.md.",
        "      The body may also be supplied on stdin. Existing skills are never",
        "      overwritten unless --replace is explicit.",
        "  skills validate <skill-or-path>",
        "      Check required frontmatter, path/name agreement, and a non-empty body.",
        "",
        "FORMAT",
        "  Skills may be flat markdown files under skills.d or directories with SKILL.md:",
        "  skills.d/research.md",
        "  skills.d/research/SKILL.md",
        "  skills.d/research/skills.d/citations/SKILL.md",
        "  skills.d/research/references/details.md",
        "  Nested skills live under a parent skill's own skills.d directory.",
        "  Prompt assembly includes only top-level skills; nested child skills are",
        "  loaded explicitly through the skills command surface.",
        "",
        "EDITING",
        "  Use `skills show` before editing. For a user-requested reusable workflow,",
        "  complete and verify it, draft a concise instruction body, run `skills create`,",
        "  then run `skills validate` and `skills show`. Do not silently persist",
        "  one-off or sensitive work. Use --replace only for an intentional revision.",
        "",
      ].join("\n");

    case "wiki":
      return [
        "WIKI(1)",
        "",
        "NAME",
        "  wiki - manage repo-backed knowledge databases",
        "",
        "OVERVIEW",
        "  `wiki` manages named repo-backed knowledge databases made of markdown pages and live source references.",
        "  Use it for broader domain knowledge, research notes, product docs, and the human-owned `personal` memory wiki.",
        "",
        "INFO",
        "  wiki info <wiki-id>",
        "      Print collection metadata and a compact folder/page tree.",
        "  wiki refresh gsv-manual",
        "      Refresh the built-in GSV Manual from its configured upstream.",
        "",
        "SEARCH",
        "  wiki search <query> [--prefix PREFIX]",
        "      Find matching notes with snippets.",
        "",
        "DATABASE SETUP",
        "  wiki db init product-alpha --title \"Product Alpha\"",
        "  GSV provisions the `personal` wiki; do not create an agent-local substitute.",
        "",
        "PAGE FILES",
        "  Wiki repos are mounted as normal files under `/src/repos/<owner>/<wiki>`.",
        "  Prefer filesystem search/read/write/edit for page work once the wiki exists.",
        "  Examples:",
        "    /src/repos/alice/personal/index.md",
        "    /src/repos/alice/personal/pages/journal/2026/06/2026-06-19.md",
        "    /src/repos/alice/personal/pages/people/bob.md",
        "",
        "LIVE SOURCES",
        "  Source references use the form:",
        "    target:/absolute/path::Optional title",
        "  Quote the whole value when the title contains spaces.",
        "  Example:",
        "    wiki source add product-alpha/pages/auth.md --source \"gsv:/home/alice/projects/gsv/specs/auth.md::Auth spec\"",
        "",
        "SOURCE-BACKED PAGES",
        "  Use ingest when you want to create a page from one or more live sources.",
        "  Example:",
        "    wiki ingest product-alpha --source \"gsv:/home/alice/projects/gsv/docs/alpha-plan.md::Alpha plan\" --title \"Adapter UX inputs\"",
        "    wiki read product-alpha/pages/adapter-ux-inputs.md",
        "",
        "PERSONAL MEMORY",
        "  Personal memory belongs to the human and is shared by every agent working for them.",
        "  Use `personal` for durable notes; stable standing facts belong in the owner's context.d/10-personal.md.",
        "  Unresolved work belongs in the r12y ledger until its user-facing loop closes.",
        "  Examples:",
        "    wiki info personal",
        "    wiki search Alice --prefix personal/pages",
        "    Search `/src/repos/alice/personal` for Alice",
        "",
      ].join("\n");

    default:
      return null;
  }
}

function manualSynopsis(command: string): string[] {
  return (nativeCommandSynopsis(command) ?? [`${command} --help`]).map((line) => `  ${line}`);
}
