export function renderManualPage(topic?: string): string | null {
  const normalized = (topic ?? "").trim().toLowerCase();

  switch (normalized) {
    case "":
    case "help":
      return [
        "GSV manual pages",
        "",
        "Available pages:",
        "  gsv   Platform model, targets, paths, and knowledge systems",
        "  targets  Discover target ids for devices, browser clients, and adapters",
        "  codemode  Run GSV tool scripts from the shell",
        "  crontab  Install, list, and remove cron tables",
        "  mcp   Connected MCP servers and tool calls",
        "  proc  Process inspection and same-owner process IPC",
        "  sched  Low-level Kernel schedule inspection",
        "  notify  User notifications and background job alerts",
        "  pkg   Package source inspection and staged edits",
        "  skills  Reusable process skills loaded from skills.d",
        "  wiki  Durable repo-backed knowledge databases",
        "",
        "Usage:",
        "  man gsv",
        "  man targets",
        "  man codemode",
        "  man crontab",
        "  man mcp",
        "  man proc",
        "  man sched",
        "  man notify",
        "  man pkg",
        "  man skills",
        "  man wiki",
        "",
      ].join("\n");

    case "crontab":
      return [
        "CRONTAB(1)",
        "",
        "NAME",
        "  crontab - install, list, and remove cron tables",
        "",
        "SYNOPSIS",
        "  crontab -l [-u user]",
        "  crontab -r [-u user]",
        "  crontab FILE [-u user]",
        "  crontab -e [-u user]",
        "",
        "FILES",
        "  /var/spool/cron/<user>  Per-user crontab.",
        "  /etc/cron.d/<name>      System crontab with an extra user field.",
        "",
        "FORMAT",
        "  minute hour day-of-month month day-of-week command",
        "  CRON_TZ=Europe/Amsterdam",
        "",
        "EXAMPLES",
        "  crontab -l",
        "  crontab jobs.cron",
        "  printf '0 9 * * * proc spawn --label daily-brief \"Prepare the daily brief.\"\\n' > /var/spool/cron/sam",
        "",
      ].join("\n");

    case "targets":
    case "devices":
      return [
        "TARGETS(1)",
        "",
        "NAME",
        "  targets - discover GSV shell and filesystem targets",
        "",
        "SYNOPSIS",
        "  targets list [--all] [--kind gsv|native-device|browser|adapter] [--search QUERY] [--limit N] [--offset N] [--json]",
        "  targets search <query> [--all] [--limit N] [--offset N] [--json]",
        "  targets show <target-id> [--json]",
        "  devices ...",
        "",
        "OVERVIEW",
        "  `targets` lists the ids accepted by target-aware Shell, filesystem, CodeMode,",
        "  and `cp source-target:/path destination-target:/path` operations. The prompt",
        "  only includes a compact target sample, so use this command when more targets",
        "  may exist.",
        "",
        "KINDS",
        "  gsv            Native cloud target.",
        "  native-device  User-owned machines and nodes.",
        "  browser        Extension-provided active browser targets.",
        "  adapter        External messaging surfaces such as WhatsApp or Discord.",
        "",
        "EXAMPLES",
        "  targets list",
        "  targets list --kind browser",
        "  targets search whatsapp",
        "  targets show rearden:brave",
        "",
      ].join("\n");

    case "mcp":
      return [
        "MCP(1)",
        "",
        "NAME",
        "  mcp - manage connected MCP servers and call MCP tools",
        "",
        "SYNOPSIS",
        "  mcp status [--json]",
        "  mcp list [--json]",
        "  mcp tools [server-id|name] [--json]",
        "  mcp describe <server-id|name> [tool-name|codemode-function] [--json]",
        "  mcp search <query> [--json]",
        "  mcp codemode [server-id|name] [--json]",
        "  mcp add <name> <url> [--transport auto|streamable-http|sse] [--callback-host origin] [--header key=value] [--json]",
        "  mcp refresh <server-id> [--json]",
        "  mcp call <server-id|name> <tool-name|codemode-function> [--arg key=value] [--args-json json] [--json]",
        "  mcp remove <server-id> [--json]",
        "",
        "OVERVIEW",
        "  `mcp` wraps sys.mcp.*. It keeps MCP behind the runtime boundary instead of",
        "  exposing every remote MCP tool as a direct model tool.",
        "  Use `mcp status` for server health, `mcp tools` or `mcp search` to discover",
        "  available tools, and `mcp codemode` to print a CodeMode discovery snippet.",
        "  Tool listings include the generated CodeMode function names used by agents.",
        "  OAuth-capable servers return auth_url from add/list; open that URL and finish",
        "  sign-in through /oauth/callback before refreshing or calling tools.",
        "",
        "EXAMPLES",
        "  mcp status",
        "  mcp add github https://mcp.github.com/mcp --transport streamable-http",
        "  mcp tools github",
        "  mcp describe github search_issues",
        "  mcp call github search_issues --args-json '{\"query\":\"gsv\"}' --json",
        "",
      ].join("\n");

    case "sched":
      return [
        "SCHED(1)",
        "",
        "NAME",
        "  sched - inspect and control low-level Kernel schedules",
        "",
        "SYNOPSIS",
        "  sched list [--all]",
        "  sched add --json JSON",
        "  sched enable <id>",
        "  sched disable <id>",
        "  sched remove <id>",
        "  sched run <id> [--force]",
        "",
        "OVERVIEW",
        "  `sched` wraps sched.* for inspection, force-runs, and compatibility.",
        "  Use crontab(1) or /var/spool/cron/<user> for normal cron jobs.",
        "",
        "EXPRESSIONS",
        "  --cron uses five Linux-style fields and an IANA timezone.",
        "  --every, --after, and proc call --timeout durations support ms, s, m, h, and d.",
        "",
      ].join("\n");

    case "proc":
      return [
        "PROC(1)",
        "",
        "NAME",
        "  proc - inspect processes and send same-owner process messages",
        "",
        "SYNOPSIS",
        "  proc self",
        "  proc list",
        "  proc agents [--json]",
        "  proc spawn [--as ACCOUNT] [--label LABEL] [--prompt TEXT] [--parent PID] [--cwd PATH] <prompt>",
        "  proc spawn --json JSON",
        "  proc segments [--pid PID] [--conversation id]",
        "  proc policy [--pid PID] [--conversation id] [--overflow auto-compact|fail] [--compact-at N] [--keep-last N]",
        "  proc history [--pid PID] [--conversation id] [--tail] [--limit N] [--offset N] [--json] [--full]",
        "  proc segment <segment-id> [--pid PID] [--conversation id] [--limit N] [--offset N] [--json]",
        "  proc compact [--pid PID] [--conversation id] (--keep-last N | --through-message-id ID) [--summary TEXT | --generate-summary]",
        "  proc fork (<segment-id> | --message-id ID) [--pid PID] [--conversation id] [--target id] [--title TITLE] [--segment-only]",
        "  proc send <pid> [--conversation id] [--metadata-json json] <message>",
        "  proc call <pid> [--conversation id] [--metadata-json json] [--timeout 60s] <message>",
        "",
        "OVERVIEW",
        "  `proc` is the process IPC userland command. It wraps proc.ipc syscalls instead",
        "  of exposing a model-specific ProcessMessage tool.",
        "",
        "COMMANDS",
        "  self",
        "      Print the current GSV process id. The same value is available as $GSV_PID.",
        "  list",
        "      Show processes visible to the current user.",
        "  agents",
        "      Show the accounts you can run a process as: your own identity, your",
        "      personal agent, enabled package agents (pkg#agent), and agent accounts",
        "      whose group you belong to.",
        "  spawn",
        "      Create a process. With no --as it inherits the caller's run-as identity",
        "      as a fresh worker (or, for a top-level interactive call, reuses your",
        "      personal-agent process). Pass --as ACCOUNT (a username, uid, or",
        "      pkg#agent) to run as a different agent account.",
        "      A prompt on spawn starts fire-and-forget work. Use proc call when",
        "      the caller needs an IPC reply from the worker.",
        "  segments",
        "      List compacted conversation archive segments for a process conversation.",
        "  policy",
        "      Show or set the visible context-overflow policy for a conversation.",
        "  history",
        "      Read the live transcript for this process or another visible process.",
        "      Output is content-bounded by default; use --full or --json for raw content.",
        "  segment",
        "      Read archived messages from a compacted segment without restoring them.",
        "  compact",
        "      Archive a conversation prefix and replace it with a visible summary marker.",
        "  fork",
        "      Branch a live conversation from a message or restore a compacted segment",
        "      into a new conversation.",
        "  send",
        "      Send asynchronous mail to another process owned by the same user.",
        "  call",
        "      Send bounded work to another process. The kernel delivers ipc.reply or",
        "      ipc.timeout back to the caller's default conversation.",
        "",
        "OPTIONS",
        "  --conversation <id>      Target process conversation. Defaults to default.",
        "  --pid <pid>              Target process for lifecycle commands. Defaults to this process.",
        "  --keep-last <n>          Compact all but the newest n messages.",
        "  --through-message-id <id> Compact through a specific message id.",
        "  --summary <text>         Markdown summary inserted into the live conversation.",
        "  --generate-summary       Ask the process model to write the compact summary.",
        "  --overflow <mode>        Policy mode: auto-compact or fail.",
        "  --compact-at <n>         Policy pressure threshold from 0 to 1.",
        "  --target <id>            Conversation id to create for proc fork.",
        "  --message-id <id>        Live message id to branch from with proc fork.",
        "  --tail                   Read the latest live history page.",
        "  --before-message-id <id> Read live history before this message id.",
        "  --after-message-id <id>  Read live history after this message id.",
        "  --segment-only           Fork only the archived segment, without the kept suffix.",
        "  --limit <n>              Maximum live or archived messages to print.",
        "  --offset <n>             Live or archived message offset.",
        "  --json                   Print raw JSON for proc history or proc segment.",
        "  --full                   Do not truncate live proc history message content.",
        "  --max-content-chars <n>  Per-message live history content budget.",
        "  --metadata-json <json>   Optional JSON object delivered with the message.",
        "  --timeout <duration>     Call deadline. Supports ms, s, and m suffixes.",
        "",
      ].join("\n");

    case "codemode":
      return [
        "CODEMODE(1)",
        "",
        "NAME",
        "  codemode - run JavaScript blocks with GSV shell and filesystem wrappers",
        "",
        "SYNOPSIS",
        "  codemode <script.js> [options] [-- argv...]",
        "  codemode run <script.js> [options] [-- argv...]",
        "  codemode -e <code> [options] [-- argv...]",
        "",
        "OVERVIEW",
        "  `codemode` runs one async JavaScript block through the same CodeMode runtime exposed",
        "  to agents. Scripts can call `await shell(input, options)`, `fs.read`, `fs.write`,",
        "  `fs.edit`, `fs.delete`, `fs.search`, and connected MCP tools as generated async",
        "  functions. The CodeMode tool includes generated TypeScript declarations for ready",
        "  MCP tools. MCP functions return structured output directly when available.",
        "  Inspect `mcpTools` for full MCP function metadata.",
        "  Script files and -e code are treated as async function bodies. Use top-level await",
        "  freely, and use an explicit return statement for the value to print.",
        "",
        "OPTIONS",
        "  --target <device>   Default target for shell and filesystem calls.",
        "  --cwd <path>        Default cwd for shell calls and relative filesystem paths.",
        "  --json              Print the full result envelope.",
        "  --arg key=value     Expose scalar args[key] to the script.",
        "  --args-json <json>  Expose structured args to the script.",
        "",
        "SCRIPT CONTEXT",
        "  argv                Positional arguments after `--`.",
        "  args                Values supplied with --arg or --args-json.",
        "  shell(input, opts)  Run or continue a shell command.",
        "  fs                  Filesystem helpers: read, write, edit, delete, search.",
        "  mcpTools            Metadata and schemas for generated MCP tool functions.",
        "",
        "RESULTS",
        "  Without --json, completed runs print only the returned value.",
        "  With --json, runs print { status, result?, error?, logs? }.",
        "  Failed runs exit 1.",
        "",
        "EXAMPLES",
        "  codemode -e 'return await shell(\"pwd\")'",
        "  codemode ./check.js --cwd ~/projects/gsv -- arg1 arg2",
        "",
      ].join("\n");

    case "gsv":
      return [
        "GSV(1)",
        "",
        "NAME",
        "  gsv - distributed AI operating environment",
        "",
        "OVERVIEW",
        "  GSV gives AI processes a Linux-like filesystem, explicit tools, and multiple execution targets.",
        "  `gsv` is the local control target. Other targets are user devices or nodes that may expose",
        "  shell and filesystem operations when they are online and authorized.",
        "",
        "STANDING CONTEXT",
        "  ~/context.d/*.md",
        "      Small curated notes that are always loaded into prompt context.",
        "  ~/skills.d/*",
        "      Reusable process skills. Prompt context lists compact skill ids;",
        "      use `skills show <skill>` to read full SKILL.md content.",
        "",
        "DURABLE KNOWLEDGE",
        "  wiki",
        "      Durable markdown knowledge lives in repo-backed wiki collections.",
        "      This is not loaded into the prompt automatically; use `wiki` or search",
        "      `/src/repos/<owner>/<wiki>` to retrieve it.",
        "",
        "KNOWN PATHS",
        "  /home/<user>   User home, including standing context and ordinary files",
        "  /var           Runtime-managed state, caches, and generated system data",
        "  /etc           System manuals and stable operator documentation",
        "  /src/packages  Visible installed package source trees",
        "  /src/repos     Visible ripgit repositories, including wiki repos",
        "  /sys           Live kernel configuration and runtime control surfaces",
        "  /proc          Live process and runtime inspection surfaces",
        "  /dev           Device-like virtual endpoints",
        "",
        "KNOWLEDGE WORKFLOWS",
        "  Use `wiki db init <id>` to create a wiki repo, then edit pages directly",
        "  under `/src/repos/<owner>/<id>` when the target note is clear.",
        "  Use source references when a page should cite live files without copying a source corpus.",
        "  Use `wiki search` to find matching notes and `wiki brief` when you want compact snippets.",
        "",
      ].join("\n");

    case "pkg":
      return [
        "PKG(1)",
        "",
        "NAME",
        "  pkg - inspect and manage packages",
        "",
        "OVERVIEW",
        "  `pkg` lists installed packages, reads package source refs and history,",
        "  scaffolds user-owned packages, and manages staged package source edits.",
        "",
        "INSPECTION",
        "  pkg list",
        "  pkg show [package]",
        "  pkg manifest [package]",
        "  pkg capabilities [package]",
        "  pkg refs [package]",
        "  pkg log [package] [--limit N] [--offset N]",
        "",
        "SOURCE FILES",
        "  /src/packages/<package>",
        "      Visible installed package source. Sources owned by the current user",
        "      are writable, but writes are staged in a process-local overlay.",
        "",
        "STAGED EDITS",
        "  pkg source status [package]",
        "  pkg source diff [package]",
        "  pkg source commit [package] --message TEXT [--branch BRANCH]",
        "  pkg source discard [package]",
        "",
        "CREATE",
        "  pkg create --repo owner/repo [--template web-ui|command] [--enable]",
        "",
      ].join("\n");

    case "skills":
      return [
        "SKILLS(1)",
        "",
        "NAME",
        "  skills - discover and read reusable process skills",
        "",
        "OVERVIEW",
        "  `skills` reads layered skills.d directories and shows reusable workflows",
        "  without dumping their full contents into every prompt. Prompt context keeps",
        "  only a compact skill index; use this command to inspect the full skill.",
        "",
        "SOURCES",
        "  ~/skills.d",
        "      Account-local skills, backed by the run-as account's home ripgit repository.",
        "  /src/packages/{package}/skills.d",
        "      Package-provided skills shipped with visible enabled packages.",
        "",
        "COMMANDS",
        "  skills list",
        "      List top-level skill ids, source labels, writable state, and descriptions.",
        "  skills list <skill>",
        "      List immediate nested child skills under a parent skill.",
        "  skills tree [skill]",
        "      Print the skill hierarchy, or a subtree rooted at a parent skill.",
        "      `skills topics` is an alias.",
        "  skills search <query>",
        "      Search ids, descriptions, and skill bodies.",
        "  skills show <skill>",
        "      Print a full SKILL.md and its backing source path.",
        "  skills files <skill>",
        "      List supporting files under the skill directory.",
        "  skills read <skill> <file>",
        "      Read a supporting file such as references/api.md or templates/app.ts.",
        "",
        "FORMAT",
        "  Skills may be flat markdown files under skills.d or directories with SKILL.md:",
        "  skills.d/package-development.md",
        "  skills.d/package-development/SKILL.md",
        "  skills.d/package-development/skills.d/create-package/SKILL.md",
        "  skills.d/package-development/references/details.md",
        "  Nested skills live under a parent skill's own skills.d directory.",
        "  Prompt assembly includes only top-level skills; nested child skills are",
        "  loaded explicitly through the skills command surface.",
        "",
        "EDITING",
        "  Use `skills show` before editing. The output includes the source path and",
        "  writable state. Home skills can be edited directly. Package",
        "  skills follow package source rules; writable package edits are staged until",
        "  `pkg source commit`.",
        "",
      ].join("\n");

    case "wiki":
      return [
        "WIKI(1)",
        "",
        "NAME",
        "  wiki - manage repo-backed knowledge databases",
        "",
        "OVERVIEW",
        "  `wiki` is provided by the Wiki package. It manages named repo-backed knowledge databases made of markdown pages and live source references.",
        "  Use it for broader domain knowledge, research notes, product docs, and the conventional per-agent `memory` database.",
        "",
        "INFO",
        "  wiki info <wiki-id>",
        "      Print collection metadata and a compact folder/page tree.",
        "",
        "SEARCH",
        "  wiki search <query> [--prefix PREFIX]",
        "      Find matching notes with snippets.",
        "",
        "DATABASE SETUP",
        "  wiki db init product-alpha --title \"Product Alpha\"",
        "  wiki db init memory --title \"Agent Memory\"",
        "",
        "PAGE FILES",
        "  Wiki repos are mounted as normal files under `/src/repos/<owner>/<wiki>`.",
        "  Prefer filesystem search/read/write/edit for page work once the wiki exists.",
        "  Examples:",
        "    /src/repos/friday/memory/index.md",
        "    /src/repos/friday/memory/pages/journal/2026/06/2026-06-19.md",
        "    /src/repos/friday/memory/pages/people/alice.md",
        "",
        "LIVE SOURCES",
        "  Source references use the form:",
        "    target:/absolute/path::Optional title",
        "  Quote the whole value when the title contains spaces.",
        "  Example:",
        "    wiki source add product-alpha/pages/auth.md --source \"gsv:/home/alice/projects/gsv/specs/auth.md::Auth spec\"",
        "",
        "SOURCE-BACKED PAGES",
        "  Use ingest when you want to create a page from one or more live sources.",
        "  Example:",
        "    wiki ingest product-alpha --source \"gsv:/home/alice/projects/gsv/docs/alpha-plan.md::Alpha plan\" --title \"Adapter UX inputs\"",
        "    wiki read product-alpha/pages/adapter-ux-inputs.md",
        "",
        "AGENT MEMORY",
        "  Use the agent's own `memory` database for durable notes about people, projects, preferences, decisions, journal entries, closed-loop history, and supporting evidence.",
        "  Keep active open loops in ~/context.d/20-open-loops.md so they are loaded into every prompt.",
        "  Examples:",
        "    wiki info memory",
        "    wiki search Alice --prefix memory/pages",
        "    Search `/src/repos/friday/memory` for Alice",
        "",
      ].join("\n");

    case "notify":
      return [
        "NOTIFY(1)",
        "",
        "NAME",
        "  notify - send and manage user notifications",
        "",
        "OVERVIEW",
        "  `notify` creates durable user notifications and manages their read/dismissed state.",
        "  Notifications appear in the web shell toast/panel and can be delivered by other surfaces later.",
        "",
        "SEND",
        "  notify send --title \"Wiki build finished\" --body \"product-alpha is ready\" --level success",
        "",
        "LIST",
        "  notify list",
        "  notify list --unread",
        "  notify list --dismissed",
        "",
        "STATE CHANGES",
        "  notify read <notification-id>",
        "  notify dismiss <notification-id>",
        "",
        "LEVELS",
        "  info, success, warning, error",
        "",
      ].join("\n");

    default:
      return null;
  }
}
