[package]
name = "gestures"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
cameras = "=0.3.2"
crossbeam-channel = "0.5"
font8x8 = "0.3.1"
gesture-engine = { path = "../../crates/gesture-engine" }
gesture-protocol = { path = "../../crates/gesture-protocol" }
minifb = "0.28.0"

[build-dependencies]
sha2 = "0.10"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[[bin]]
name = "gsv-vision"
path = "src/main.rs"

[lints.clippy]
unwrap_used = "warn"
panic = "warn"
todo = "warn"
dbg_macro = "warn"
