/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f79e1acb9f277daf000ee8066c8651f7)
interface __BaseEnv_Env {
	PROFILES: R2Bucket;
	BROWSER: BrowserRun;
	BROWSER_LIMITS: {"enabled":false,"concurrentInstances":0,"periodSeconds":0,"maxInstanceSeconds":1800,"savedProfiles":0,"profileStorageBytes":5242880};
	INSTANCES: DurableObjectNamespace<import("./src/index").InstanceCoordinator>;
	INSTALLATION_DIRECTORY: Fetcher /* gsv-installations */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "InstanceCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BROWSER_LIMITS">> {}
}
