/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 324de302050ec3734e30ac529b14515c)
interface __BaseEnv_Env {
	ACCOUNT_DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	GSV_ACCOUNT_ORIGIN: "https://accounts.gsv.space";
	GSV_BASE_DOMAIN: "gsv.space";
	GSV_EMAIL_FROM: "noreply@gsv.space";
	GSV_RP_NAME: "GSV";
	GSV_BILLING_PLAN_KEY: "founding-monthly";
	GSV_BILLING_CURRENCY: "usd";
	GSV_BILLING_MONTHLY_PRICE_MINOR: "2000";
	GSV_BILLING_INFERENCE_BUDGET_MICROUNITS: "5000000";
	GSV_BILLING_STORAGE_LIMIT_BYTES: "10737418240";
	GSV_BILLING_PAST_DUE_GRACE_MS: "604800000";
	GSV_BILLING_RETENTION_MS: "2592000000";
	ENVIRONMENT: "production";
	TURNSTILE_SECRET: string;
	GSV_TURNSTILE_SITE_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	GSV_STRIPE_FOUNDING_PRICE_ID: string;
	GSV_STRIPE_MERCHANT_MODE: string;
	GATEWAY: Service /* entrypoint GatewayEntrypoint from gsv-managed-gateway */;
	MANAGED_TELEGRAM: Service /* entrypoint ManagedTelegramChannel from gsv-managed-telegram */;
	MANAGED_INFERENCE: Service /* entrypoint InferenceService from gsv-inference */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GSV_ACCOUNT_ORIGIN" | "GSV_BASE_DOMAIN" | "GSV_EMAIL_FROM" | "GSV_RP_NAME" | "GSV_BILLING_PLAN_KEY" | "GSV_BILLING_CURRENCY" | "GSV_BILLING_MONTHLY_PRICE_MINOR" | "GSV_BILLING_INFERENCE_BUDGET_MICROUNITS" | "GSV_BILLING_STORAGE_LIMIT_BYTES" | "GSV_BILLING_PAST_DUE_GRACE_MS" | "GSV_BILLING_RETENTION_MS" | "ENVIRONMENT" | "TURNSTILE_SECRET" | "GSV_TURNSTILE_SITE_KEY" | "STRIPE_SECRET_KEY" | "STRIPE_WEBHOOK_SECRET" | "GSV_STRIPE_FOUNDING_PRICE_ID" | "GSV_STRIPE_MERCHANT_MODE">> {}
}
