import type { RpcMethod, Handler } from "../../protocol/methods";
import {
  handleSessionGet,
  handleSessionReset,
  handleSessionStats,
  handleSessionHistory,
  handleSessionPreview,
  handleSessionPatch,
  handleSessionCompact,
  handleSessionsList,
} from "./session";
import {
  handleChannelsList,
  handleChannelInbound,
  handleChannelStart,
  handleChannelStop,
  handleChannelStatus,
  handleChannelLogin,
  handleChannelLogout,
} from "./channel";
import {
  handleToolsList,
  handleNodeExecEvent,
  handleToolRequest,
  handleToolInvoke,
  handleToolResult,
  handleNodeForget,
} from "./tools";
import { handleLogsGet, handleLogsResult } from "./logs";
import { handlePairList, handlePairApprove, handlePairReject } from "./pairing";
import { handleChatSend } from "./chat";
import {
  handleHeartbeatStart,
  handleHeartbeatStatus,
  handleHeartbeatTrigger,
} from "./heartbeat";
import {
  handleCronStatus,
  handleCronList,
  handleCronAdd,
  handleCronUpdate,
  handleCronRemove,
  handleCronRun,
  handleCronRuns,
} from "./cron";
import { handleConfigGet, handleConfigSet } from "./config";
import { handleConnect } from "./connect";
import { handleSkillsStatus, handleSkillsUpdate } from "./skills";
import {
  handleWorkspaceList,
  handleWorkspaceRead,
  handleWorkspaceWrite,
  handleWorkspaceDelete,
} from "./workspace";
import {
  handleTransferMeta,
  handleTransferAccept,
  handleTransferComplete,
  handleTransferDone,
} from "./transfer";
import {
  handleConversationBindingPut,
  handleConversationBindingRemove,
  handleConversationBindingsList,
  handleInviteClaim,
  handleInviteCreate,
  handleInviteList,
  handleInviteRevoke,
  handlePendingBindingResolve,
  handlePendingBindingsList,
  handlePrincipalProfileDelete,
  handlePrincipalProfileGet,
  handlePrincipalProfileList,
  handlePrincipalProfilePut,
  handleRegistryBackfill,
  handleRegistryRepair,
  handleSpaceMemberPut,
  handleSpaceMemberRemove,
  handleSpaceMembersList,
} from "./registry";

export function buildRpcHandlers(): Partial<{ [M in RpcMethod]: Handler<M> }> {
  return {
    connect: handleConnect,
    "tool.invoke": handleToolInvoke,
    "tool.result": handleToolResult,
    "node.exec.event": handleNodeExecEvent,
    "tools.list": handleToolsList,
    "logs.get": handleLogsGet,
    "logs.result": handleLogsResult,
    "session.get": handleSessionGet,
    "session.reset": handleSessionReset,
    "session.stats": handleSessionStats,
    "session.history": handleSessionHistory,
    "session.preview": handleSessionPreview,
    "session.patch": handleSessionPatch,
    "session.compact": handleSessionCompact,
    "sessions.list": handleSessionsList,
    "channels.list": handleChannelsList,
    "channel.inbound": handleChannelInbound,
    "channel.start": handleChannelStart,
    "channel.stop": handleChannelStop,
    "channel.status": handleChannelStatus,
    "channel.login": handleChannelLogin,
    "channel.logout": handleChannelLogout,
    "config.get": handleConfigGet,
    "config.set": handleConfigSet,
    "skills.status": handleSkillsStatus,
    "skills.update": handleSkillsUpdate,
    "heartbeat.trigger": handleHeartbeatTrigger,
    "heartbeat.status": handleHeartbeatStatus,
    "heartbeat.start": handleHeartbeatStart,
    "cron.status": handleCronStatus,
    "cron.list": handleCronList,
    "cron.add": handleCronAdd,
    "cron.update": handleCronUpdate,
    "cron.remove": handleCronRemove,
    "cron.run": handleCronRun,
    "cron.runs": handleCronRuns,
    "pair.list": handlePairList,
    "pair.approve": handlePairApprove,
    "pair.reject": handlePairReject,
    "principal.profile.get": handlePrincipalProfileGet,
    "principal.profile.list": handlePrincipalProfileList,
    "principal.profile.put": handlePrincipalProfilePut,
    "principal.profile.delete": handlePrincipalProfileDelete,
    "space.members.list": handleSpaceMembersList,
    "space.member.put": handleSpaceMemberPut,
    "space.member.remove": handleSpaceMemberRemove,
    "conversation.bindings.list": handleConversationBindingsList,
    "conversation.binding.put": handleConversationBindingPut,
    "conversation.binding.remove": handleConversationBindingRemove,
    "invite.create": handleInviteCreate,
    "invite.list": handleInviteList,
    "invite.revoke": handleInviteRevoke,
    "invite.claim": handleInviteClaim,
    "pending.bindings.list": handlePendingBindingsList,
    "pending.binding.resolve": handlePendingBindingResolve,
    "registry.backfill": handleRegistryBackfill,
    "registry.repair": handleRegistryRepair,
    "tool.request": handleToolRequest,
    "node.forget": handleNodeForget,
    "chat.send": handleChatSend,
    "workspace.list": handleWorkspaceList,
    "workspace.read": handleWorkspaceRead,
    "workspace.write": handleWorkspaceWrite,
    "workspace.delete": handleWorkspaceDelete,
    "transfer.meta": handleTransferMeta,
    "transfer.accept": handleTransferAccept,
    "transfer.complete": handleTransferComplete,
    "transfer.done": handleTransferDone,
  };
}
