// Active doticons subset used by the web UI.
// SVG masks live in web/public/icons/doticons/<name>.svg and, when available,
// web/public/icons/doticons/16/<name>.svg.
export const DOTICONS: string[] = [
  "apple",
  "box",
  "branch",
  "camera",
  "chat",
  "chrome",
  "circlePause",
  "circlePlay",
  "close",
  "cog",
  "file",
  "folder",
  "messenger",
  "microphone",
  "pencil",
  "redhat",
  "satellite",
  "stars",
  "vimeo",
  "volume",
  "weblink",
  "windows",
];
