// Generated by generate.ts from the current prompt and skill sources.
// Run generate.ts --check to detect a stale review snapshot.
window.GSV_CONTEXT_REVIEW_SNAPSHOT = {
  "schemaVersion": 1,
  "sourceFingerprint": "d621bacb7988",
  "title": "Default personal-agent context",
  "scope": "First Chat message after the web setup wizard completes",
  "defaultScenario": {
    "userUsername": "alex",
    "agentUsername": "friday",
    "currentDate": "",
    "timezone": "Europe/Amsterdam",
    "targets": "- gsv",
    "mcpServers": "- (none)",
    "firstMessage": "Hello"
  },
  "groups": [
    {
      "id": "system",
      "label": "System config",
      "shortLabel": "System",
      "rootTag": "system",
      "pathTemplate": "/sys/config/ai/context.d",
      "access": "root-managed config",
      "color": "blue"
    },
    {
      "id": "program",
      "label": "Personal-agent home",
      "shortLabel": "Agent home",
      "rootTag": "program",
      "pathTemplate": "{{program.home}}/context.d",
      "access": "user-editable home files",
      "color": "amber"
    },
    {
      "id": "skills",
      "label": "Available skills",
      "shortLabel": "Skills",
      "rootTag": null,
      "pathTemplate": "{{user.home}}/skills.d",
      "access": "derived index",
      "color": "violet"
    }
  ],
  "blocks": [
    {
      "id": "system:00-runtime.md",
      "group": "system",
      "filename": "00-runtime.md",
      "runtimePath": "/sys/config/ai/context.d/00-runtime.md",
      "template": "You are running inside GSV as agent `{{program.username}}` for owner `{{user.username}}`.\n\nAgent home: {{program.home}}\nOwner home: {{user.home}}\nCurrent working directory: {{program.cwd}}\nDate: {{current.date}}\nTimezone: {{current.timezone}}\n\nAvailable targets:\n{{targets}}\n\nReady MCP servers:\n{{mcpServers}}",
      "defaultIncluded": true,
      "kind": "live-config",
      "note": "Rendered at run start with owner, agent, date, timezone, targets, and ready MCP servers.",
      "sourceRefs": [
        {
          "path": "gateway/src/prompts/system.ts",
          "line": 22,
          "label": "prompt template"
        },
        {
          "path": "gateway/src/process/context/providers/system.ts",
          "line": 39,
          "label": "runtime rendering"
        }
      ]
    },
    {
      "id": "system:01-gsv.md",
      "group": "system",
      "filename": "01-gsv.md",
      "runtimePath": "/sys/config/ai/context.d/01-gsv.md",
      "template": "GSV is a personal intelligence OS. It has its own lightweight Linux virtual computer, exposed as the `gsv` target.\nThe user can connect their own machines (a.k.a. targets), giving you simultaneous access through the same tools by simply picking what target to run on.\n\nUser machines are any hardware that follows GSV's file system + shell abstraction. They could be traditional computers or pseudo-computers, e.g., the GSV browser extension exposes a user's browser by giving it a fs and shell for you to interact with. Use `skills show browser-target` for more details.\n\nFor more detailed information on GSV, configuration, the cloud computer, agent instances being processes, etc., use the skills and/or wiki.\n\nMessages beginning with `[Process Event]:` are GSV runtime events, not messages from your user. Treat them as system notifications.",
      "defaultIncluded": true,
      "kind": "live-config",
      "note": "A ConfigStore default read on every new run; an explicit system config value can override it.",
      "sourceRefs": [
        {
          "path": "gateway/src/prompts/system.ts",
          "line": 2,
          "label": "prompt text"
        },
        {
          "path": "gateway/src/kernel/config.ts",
          "line": 90,
          "label": "default config mapping"
        }
      ]
    },
    {
      "id": "system:05-targets.md",
      "group": "system",
      "filename": "05-targets.md",
      "runtimePath": "/sys/config/ai/context.d/05-targets.md",
      "template": "External messaging surfaces such as Telegram, WhatsApp, etc. are discovered with `message destinations`.\nYour final response returns to its origin automatically; use `message attach PATH...` to include files in that response. `message send` is only for an additional or cross-channel text/file delivery.\nFiles can be moved between targets with target-aware copy, `cp source-target:/path destination-target:/path`.\nUse `targets list` to discover target ids beyond the compact prompt list.\n\nAll of these commands must be run from the `gsv` target.",
      "defaultIncluded": true,
      "kind": "live-config",
      "note": "Shared target and delivery guidance from the operator-managed system context.",
      "sourceRefs": [
        {
          "path": "gateway/src/prompts/system.ts",
          "line": 13,
          "label": "prompt text"
        },
        {
          "path": "gateway/src/kernel/config.ts",
          "line": 91,
          "label": "default config mapping"
        }
      ]
    },
    {
      "id": "system:20-discovery.md",
      "group": "system",
      "filename": "20-discovery.md",
      "runtimePath": "/sys/config/ai/context.d/20-discovery.md",
      "template": "Before guessing GSV capabilities or command syntax, run `man --search -- '<plain-language goal>'` on target `gsv` and follow its `NEXT` action. Use `man <command>` for exact syntax.\n\nMCP integrations are usable through the `mcp` command or through CodeMode as `mcpTools`.\n\nLoad the relevant skill before following a specialized workflow.",
      "defaultIncluded": true,
      "kind": "live-config",
      "note": "Shared GSV command, MCP, and skill discovery guidance.",
      "sourceRefs": [
        {
          "path": "gateway/src/prompts/system.ts",
          "line": 38,
          "label": "prompt text"
        },
        {
          "path": "gateway/src/kernel/config.ts",
          "line": 92,
          "label": "default config mapping"
        }
      ]
    },
    {
      "id": "system:30-process-orchestration.md",
      "group": "system",
      "filename": "30-process-orchestration.md",
      "runtimePath": "/sys/config/ai/context.d/30-process-orchestration.md",
      "template": "For work that should run in another process or at a later or recurring time, use GSV process and scheduling commands on target `gsv`.\n\nUse `proc delegate` when a result must return, `proc spawn` for fire-and-forget work, and `sched` or `crontab` for scheduled work. Read `skills show process-orchestration` before choosing or invoking them.",
      "defaultIncluded": true,
      "kind": "live-config",
      "note": "A compact pointer to the process-orchestration skill for delegation and scheduling.",
      "sourceRefs": [
        {
          "path": "gateway/src/prompts/system.ts",
          "line": 46,
          "label": "prompt text"
        },
        {
          "path": "gateway/src/kernel/config.ts",
          "line": 93,
          "label": "default config mapping"
        }
      ]
    },
    {
      "id": "program:00-boot.md",
      "group": "program",
      "filename": "00-boot.md",
      "runtimePath": "{{program.home}}/context.d/00-boot.md",
      "template": "This GSV was just created. Treat this as a one-time onboarding assignment.\n\n- Get to know the user enough to be useful.\n- Help the user and your own agent account finish setting up GSV: connect useful devices/targets or messengers, configure models and approvals.\n- When the user says onboarding or setup is done, delete `~/context.d/00-boot.md` so this one-time assignment does not appear in future conversations. Until onboarding is complete, keep it as an active assignment even if the conversation changes topic.\n",
      "defaultIncluded": true,
      "kind": "seeded-home",
      "note": "Still present on the first Chat turn. sys.setup seeds it for a personal agent and does not remove it when the web wizard finishes.",
      "sourceRefs": [
        {
          "path": "gateway/src/prompts/agent-home.ts",
          "line": 16,
          "label": "seed template"
        },
        {
          "path": "gateway/src/kernel/accounts.ts",
          "line": 203,
          "label": "personal-agent seed decision"
        }
      ]
    },
    {
      "id": "program:00-style.md",
      "group": "program",
      "filename": "00-style.md",
      "runtimePath": "{{program.home}}/context.d/00-style.md",
      "template": "Answer like a helpful human in the medium you're in. Lead with the direct answer or recommendation in 1-3 sentences. Only add detail when it changes the decision, explains the key reason, or the user asks for more. Avoid \"slop grenades\": long, generic, technically correct responses that force the reader to extract the point themselves.\n\n# Example\n\nUser: \"Should we use Redis or Memcached?\"\n\nBad: Great question! The choice between Redis and Memcached is a nuanced decision that requires careful consideration of multiple factors. Let me break down the key differences: Redis offers a rich set of data structures including strings, hashes, lists, sets, and sorted sets, which provide flexibility for various use cases. It supports persistence through RDB snapshots and AOF logs, enabling data durability...\n\nGood: Redis. We need pub/sub for the notifications feature.\n",
      "defaultIncluded": true,
      "kind": "seeded-home",
      "note": "Seeded into the agent home. Exact generated copies are upgraded while user-edited copies are preserved.",
      "sourceRefs": [
        {
          "path": "gateway/src/prompts/agent-home.ts",
          "line": 39,
          "label": "seed text"
        },
        {
          "path": "gateway/src/kernel/account-home.ts",
          "line": 52,
          "label": "home seeding"
        }
      ]
    },
    {
      "id": "program:15-memory.md",
      "group": "program",
      "filename": "15-memory.md",
      "runtimePath": "{{program.home}}/context.d/15-memory.md",
      "template": "# Memory\n\nGSV has two kinds of memory:\n\n- The `memory` wiki stores durable, searchable information that you retrieve when needed.\n- Files in `~/context.d/` are standing memory loaded into every prompt.\n\nKeep standing memory small. If an active commitment or unresolved task must remain visible, create `~/context.d/20-open-loops.md` and remove it once resolved.\n\nRead `skills show memory` for memory workflows.\n",
      "defaultIncluded": true,
      "kind": "seeded-home",
      "note": "A compact introduction to searchable wiki memory and always-loaded standing memory.",
      "sourceRefs": [
        {
          "path": "gateway/src/prompts/agent-home.ts",
          "line": 103,
          "label": "seed template"
        },
        {
          "path": "gateway/src/kernel/account-home.ts",
          "line": 54,
          "label": "home seeding"
        }
      ]
    },
    {
      "id": "skills:available-skills",
      "group": "skills",
      "tagName": "available_skills",
      "runtimePath": "owner ~/skills.d index",
      "template": "Available skills are top-level only. Use `skills list <skill>` or `skills tree <skill>` to inspect nested skills.\nUse `skills show <skill>` before relying on a reusable workflow.\n\n<skill>\n<name>browser-target</name>\n<description>Use extension-provided browser targets to inspect and operate active browser state through the target's advertised filesystem and shell commands.</description>\n</skill>\n<skill>\n<name>gsv-manual</name>\n<description>Use the GSV Manual for questions about GSV's operating model, user workflows, settings, devices, users and agents, packages, automation, integrations, filesystem, desktop, updates, and source/debug orientation.</description>\n</skill>\n<skill>\n<name>gsv-package-development</name>\n<description>Guide on how to build and modify GSV packages, including source checkout, app/backend/CLI changes, manifests, validation, staged commits, and syncing.</description>\n</skill>\n<skill>\n<name>gsv-package-review</name>\n<description>Guide on how to review GSV packages before approval, including source inspection, manifests, capabilities, entrypoints, staged edits, refs, and trust boundaries.</description>\n</skill>\n<skill>\n<name>memory</name>\n<description>Store, retrieve, and organize GSV agent memory. Use for durable facts, preferences, decisions, journal notes, project background, or active commitments that may need standing context.</description>\n</skill>\n<skill>\n<name>process-orchestration</name>\n<description>Choose and use GSV delegation, subprocess, IPC, scheduling, and cron workflows. Use when work should run in another process or at a later or recurring time.</description>\n</skill>\n<skill>\n<name>skill-authoring</name>\n<description>Create or revise reusable GSV agent workflows under skills.d. Use when the user asks to automate, save, teach, repeat, or reuse a workflow, or accepts an offer to preserve a proven workflow for later.</description>\n</skill>",
      "defaultIncluded": true,
      "kind": "derived-index",
      "note": "Not context.d: rendered from the top-level skills seeded into the human owner's home during bootstrap.",
      "sourceRefs": [
        {
          "path": "gateway/src/kernel/skills.ts",
          "line": 289,
          "label": "index renderer"
        },
        {
          "path": "gateway/src/kernel/sys/skills-seed.ts",
          "line": 19,
          "label": "bootstrap seeding"
        },
        {
          "path": "skills/browser-target/SKILL.md",
          "line": 3,
          "label": "browser-target description"
        },
        {
          "path": "skills/gsv-manual/SKILL.md",
          "line": 3,
          "label": "gsv-manual description"
        },
        {
          "path": "skills/gsv-package-development/SKILL.md",
          "line": 3,
          "label": "gsv-package-development description"
        },
        {
          "path": "skills/gsv-package-review/SKILL.md",
          "line": 3,
          "label": "gsv-package-review description"
        },
        {
          "path": "skills/memory/SKILL.md",
          "line": 3,
          "label": "memory description"
        },
        {
          "path": "skills/process-orchestration/SKILL.md",
          "line": 3,
          "label": "process-orchestration description"
        },
        {
          "path": "skills/skill-authoring/SKILL.md",
          "line": 3,
          "label": "skill-authoring description"
        }
      ]
    }
  ],
  "skillEntries": [
    {
      "id": "browser-target",
      "name": "browser-target",
      "description": "Use extension-provided browser targets to inspect and operate active browser state through the target's advertised filesystem and shell commands."
    },
    {
      "id": "gsv-manual",
      "name": "gsv-manual",
      "description": "Use the GSV Manual for questions about GSV's operating model, user workflows, settings, devices, users and agents, packages, automation, integrations, filesystem, desktop, updates, and source/debug orientation."
    },
    {
      "id": "gsv-package-development",
      "name": "gsv-package-development",
      "description": "Guide on how to build and modify GSV packages, including source checkout, app/backend/CLI changes, manifests, validation, staged commits, and syncing."
    },
    {
      "id": "gsv-package-review",
      "name": "gsv-package-review",
      "description": "Guide on how to review GSV packages before approval, including source inspection, manifests, capabilities, entrypoints, staged edits, refs, and trust boundaries."
    },
    {
      "id": "memory",
      "name": "memory",
      "description": "Store, retrieve, and organize GSV agent memory. Use for durable facts, preferences, decisions, journal notes, project background, or active commitments that may need standing context."
    },
    {
      "id": "process-orchestration",
      "name": "process-orchestration",
      "description": "Choose and use GSV delegation, subprocess, IPC, scheduling, and cron workflows. Use when work should run in another process or at a later or recurring time."
    },
    {
      "id": "skill-authoring",
      "name": "skill-authoring",
      "description": "Create or revise reusable GSV agent workflows under skills.d. Use when the user asks to automate, save, teach, repeat, or reuse a workflow, or accepts an offer to preserve a proven workflow for later."
    }
  ],
  "notIncluded": [
    {
      "id": "owner-context",
      "title": "Owner home context",
      "pathTemplate": "{{user.home}}/context.d/*.md",
      "status": "empty on a fresh setup",
      "explanation": "The human home is created with directory markers and seeded skills, but no default Markdown context files. The owner provider therefore emits no <user> root on the first turn.",
      "sourceRefs": [
        {
          "path": "gateway/src/process/context/providers/owner.ts",
          "line": 10,
          "label": "owner provider"
        },
        {
          "path": "gateway/src/kernel/sys/setup.ts",
          "line": 309,
          "label": "fresh human cleanup"
        }
      ]
    }
  ],
  "trace": [
    {
      "label": "Run input",
      "detail": "The Process DO resolves ai.config and ai.tools once, then asks the context assembler for systemPrompt.",
      "sourceRef": {
        "path": "gateway/src/process/do.ts",
        "line": 4176,
        "label": "first-tick assembly"
      }
    },
    {
      "label": "Provider order",
      "detail": "system → personal-agent home → human owner home → skills",
      "sourceRef": {
        "path": "gateway/src/process/context/selection.ts",
        "line": 12,
        "label": "provider selection"
      }
    },
    {
      "label": "Final serialization",
      "detail": "Context roots are grouped first; regular sections such as available_skills follow. Empty files and roots disappear.",
      "sourceRef": {
        "path": "gateway/src/process/context/assembly.ts",
        "line": 4,
        "label": "prompt serializer"
      }
    },
    {
      "label": "Adjacent model input",
      "detail": "The first user message is separately annotated with its source and reply destination; seven syscall tool schemas are another field, not part of systemPrompt.",
      "sourceRef": {
        "path": "gateway/src/process/do.ts",
        "line": 5705,
        "label": "message annotation"
      }
    }
  ]
};
