/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5d468c2c42e6b7ac544c42c8cd19b625)
interface __BaseEnv_Env {
	ENVIRONMENT: "production";
	MANAGED_INFERENCE_PROVIDER: "disabled";
	MANAGED_MAX_CONCURRENT: "2";
	MANAGED_DAILY_BUDGET_MICROUNITS: "500000";
	MANAGED_MAX_ATTEMPTS: "3";
	BUDGET_COORDINATOR: DurableObjectNamespace<import("./src/index").BudgetCoordinator>;
	ENTITLEMENTS: Service /* entrypoint EntitlementReaderEntrypoint from gsv-accounts */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BudgetCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "MANAGED_INFERENCE_PROVIDER" | "MANAGED_MAX_CONCURRENT" | "MANAGED_DAILY_BUDGET_MICROUNITS" | "MANAGED_MAX_ATTEMPTS">> {}
}
