/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.dev.jsonc --include-runtime=false` (hash: 0051ae17c87a55ecda38a452c1335c2f)
interface __BaseEnv_Env {
	OPENROUTER_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_API_KEY">> {}
}
