/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f4ac7d0f9acd3f2291a75cc1d06f8648)
interface __BaseEnv_Env {
	MANAGED_INFERENCE_ENABLED: true;
	MANAGED_INFERENCE_MONTHLY_LIMIT_NANO_USD: 0;
	OPENROUTER_API_KEY: string;
	INFERENCE_INSTALLATIONS: DurableObjectNamespace<import("./src/index").InferenceInstallation>;
	ACCOUNTS: Fetcher /* gsv-accounts */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "InferenceInstallation";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MANAGED_INFERENCE_ENABLED" | "MANAGED_INFERENCE_MONTHLY_LIMIT_NANO_USD" | "OPENROUTER_API_KEY">> {}
}
