import { defineAppManifest } from "./app-sdk";
import type { AppCapability, AppIcon, AppManifest, AppWindowDefaults, DesktopIconId } from "./app-sdk";

export type { AppCapability, AppIcon, AppManifest, AppWindowDefaults, DesktopIconId };

export const APP_REGISTRY: readonly AppManifest[] = [
  defineAppManifest({
    id: "chat",
    name: "Chat",
    description: "Conversational workspace with agents.",
    icon: { kind: "builtin", id: "chat" },
    entrypoint: { kind: "component", route: "/apps/chat", tagName: "gsv-chat-app" },
    permissions: ["chat.use"],
    syscalls: ["proc.spawn", "proc.send", "proc.history", "sys.workspace.list"],
    windowDefaults: {
      width: 880,
      height: 640,
      minWidth: 620,
      minHeight: 420,
    },
  }),
  defineAppManifest({
    id: "shell",
    name: "Shell",
    description: "Interactive command shell for nodes.",
    icon: { kind: "builtin", id: "shell" },
    entrypoint: { kind: "component", route: "/apps/shell", tagName: "gsv-shell-app" },
    permissions: ["shell.exec", "device.inspect"],
    syscalls: ["shell.exec", "sys.device.list"],
    windowDefaults: {
      width: 980,
      height: 640,
      minWidth: 700,
      minHeight: 420,
    },
  }),
  defineAppManifest({
    id: "devices",
    name: "Devices",
    description: "Connected machine inventory and runtime device status.",
    icon: { kind: "builtin", id: "devices" },
    entrypoint: { kind: "component", route: "/apps/devices", tagName: "gsv-devices-app" },
    permissions: ["device.inspect"],
    syscalls: ["sys.device.list", "sys.device.get"],
    windowDefaults: {
      width: 940,
      height: 620,
      minWidth: 720,
      minHeight: 460,
    },
  }),
  defineAppManifest({
    id: "processes",
    name: "Processes",
    description: "Inspect and manage running agent processes.",
    icon: { kind: "builtin", id: "processes" },
    entrypoint: { kind: "component", route: "/apps/processes", tagName: "gsv-processes-app" },
    permissions: ["proc.inspect"],
    syscalls: ["proc.list", "proc.kill"],
    windowDefaults: {
      width: 920,
      height: 620,
      minWidth: 700,
      minHeight: 440,
    },
  }),
  defineAppManifest({
    id: "files",
    name: "Files",
    description: "File browser and workspace management.",
    icon: { kind: "builtin", id: "files" },
    entrypoint: { kind: "component", route: "/apps/files", tagName: "gsv-files-app" },
    permissions: ["fs.*", "device.inspect"],
    syscalls: ["fs.read", "fs.search", "fs.write", "fs.edit", "fs.delete", "sys.device.list"],
    windowDefaults: {
      width: 980,
      height: 650,
      minWidth: 720,
      minHeight: 460,
    },
  }),
  defineAppManifest({
    id: "packages",
    name: "Packages",
    description: "Browse built-in packages and scaffold install flows.",
    icon: { kind: "builtin", id: "packages" },
    entrypoint: { kind: "component", route: "/apps/packages", tagName: "gsv-packages-app" },
    permissions: [],
    syscalls: ["pkg.list"],
    windowDefaults: {
      width: 920,
      height: 620,
      minWidth: 700,
      minHeight: 460,
    },
  }),
  defineAppManifest({
    id: "control",
    name: "Control",
    description: "System status, permissions, and settings.",
    icon: { kind: "builtin", id: "control" },
    entrypoint: { kind: "component", route: "/apps/control", tagName: "gsv-control-app" },
    permissions: ["system.manage", "proc.inspect"],
    syscalls: [
      "sys.config.get",
      "sys.config.set",
      "sys.token.create",
      "sys.token.list",
      "sys.token.revoke",
      "sys.link",
      "sys.unlink",
      "sys.link.list",
      "sys.link.consume",
      "adapter.connect",
      "adapter.disconnect",
      "adapter.status",
    ],
    windowDefaults: {
      width: 860,
      height: 580,
      minWidth: 640,
      minHeight: 420,
    },
  }),
] as const;
