export type {
  AdapterService,
  AdapterServiceCapabilities,
  AdapterServiceDescriptor,
} from "../../../packages/gsv/src/services/adapters.js";
export type {
  AdapterAccountStatus,
  AdapterActivity,
  AdapterActor,
  AdapterConnectChallenge,
  AdapterConnectConfig,
  AdapterInstallationContext,
  AdapterGatewayFrame as GatewayFrame,
  AdapterGatewayRequestFrame as GatewayRequestFrame,
  AdapterGatewayResponseFrame as GatewayResponseFrame,
  AdapterInboundMessage,
  AdapterInboundResult,
  AdapterMedia,
  AdapterMediaBody,
  AdapterOutboundMessage,
  AdapterDeliveryContext,
  AdapterLinkedPeerContext,
  AdapterPairingActivateInput,
  AdapterPairingCandidate,
  AdapterPairingDisconnectInput,
  AdapterPairingDisconnectResult,
  AdapterPairingFinalizeInput,
  AdapterPairingInfo,
  AdapterPairingPreparation,
  AdapterPairingPrepareInput,
  AdapterPairingRoute,
  AdapterPairingRouteScope,
  AdapterPairingWorkerInterface,
  AdapterSurface,
  AdapterSurfaceKind,
  AdapterWorkerConnectResult as AdapterConnectResult,
  AdapterWorkerDisconnectResult as AdapterDisconnectResult,
  AdapterProviderSendResult as AdapterSendResult,
} from "../../../packages/gsv/src/protocol/adapters.js";
export type { BinaryBody } from "../../../packages/gsv/src/protocol/body.js";
export type { ProcHilRequest } from "../../../packages/gsv/src/protocol/syscalls/proc.js";
