export type {
  AdapterAccountStatus,
  AdapterActivity,
  AdapterActor,
  AdapterConnectChallenge,
  AdapterGatewayFrame as GatewayFrame,
  AdapterGatewayRequestFrame as GatewayRequestFrame,
  AdapterGatewayResponseFrame as GatewayResponseFrame,
  AdapterInboundMessage,
  AdapterInboundResult,
  AdapterMedia,
  AdapterMediaBody,
  AdapterOutboundMessage,
  AdapterSurface,
  AdapterSurfaceKind,
  AdapterWorkerConnectResult as AdapterConnectResult,
  AdapterWorkerDisconnectResult as AdapterDisconnectResult,
  AdapterWorkerInterface,
  AdapterWorkerSendResult as AdapterSendResult,
} from "../../../packages/gsv/src/protocol/adapters.js";
export type { BinaryBody } from "../../../packages/gsv/src/protocol/body.js";
